### ISSUE TITLE
Can display some screenshots of the software's interface on Readme？

### ISSUE THREAD

**Issue by xh542428798** [JakubMelka/PDF4QT#101]
Great! This is exactly what I've been looking for. I want an open-source PDF editor and I've been searching for it for a while. Thank you for sharing this project. Additionally, may I ask if it is possible to display some screenshots of the software's interface and features on the homepage?

**Comment by raffaem** [comment]
https://jakubmelka.github.io/screenshots/

**Comment by JakubMelka** [comment]
Hello, I am happy that you are happy. Screenshots are on the web page in the special section.
