### ISSUE TITLE
Bookmark sidebar greyed out if a bookmark is not already present

### ISSUE THREAD

**Issue by raffaem** [JakubMelka/PDF4QT#103]
If at least one bookmark is not already present, the "Bookmarks" sidebar is greyed out and you can't add your first bookmark :(

Take the following PDF as an example:

[exponents_properties.pdf](https://github.com/JakubMelka/PDF4QT/files/13253965/exponents_properties.pdf)

**Comment by raffaem** [comment]
Also, when you open the "Bookmarks" sidebar, the icon stays grey instead of being colored

**Comment by JakubMelka** [comment]
Implemented.
