### ISSUE TITLE
pdf_3d branch and license

### ISSUE THREAD

**Issue by raffaem** [JakubMelka/PDF4QT#104]
The pdf_3d branch contains a LICENSE.rtf, which is the source of a "Unknown licenses found" on the home page.

![image](https://github.com/JakubMelka/PDF4QT/assets/54762742/5adaf393-5559-4999-a4d4-d051e285e847)

Would it be possible to delete the branch if it is not useful anymore? Or at least delete that file

Best

**Comment by JakubMelka** [comment]
Hello, @raffaem , I have removed it, but unfortunately, nothing happened and text remained here.

**Comment by raffaem** [comment]
> Hello, @raffaem , I have removed it, but unfortunately, nothing happened and text remained here.

Maybe the tags?

I believe v1.2.0 and v1.2.1 still has it

**Comment by JakubMelka** [comment]
@raffaem , I have deleted these tags but it is still here.

**Comment by JakubMelka** [comment]
@raffaem, it seems to be fixed.
