### ISSUE TITLE
Pdf4QtDocPageOrganizer: Crash when adding image

### ISSUE THREAD

**Issue by cweiske** [JakubMelka/PDF4QT#105]
I tried to use `Pdf4QtDocPageOrganizer` to combine 10 jpg images to one pdf, and it crashed.

Steps to reproduce:
1. Open Pdf4QtDocPageOrganizer
2. Click menu Insert > Insert Image and select a .jpg file, "Open"
3. Crash

Backtrace is not useful:
```
(gdb) bt full
#0  ____longjmp_chk () at ../sysdeps/unix/sysv/linux/x86_64/____longjmp_chk.S:168
#1  0x4629de20b8735d0f in  ()
```

I am using PDF4QT 1.3.5, installed from the official .deb package.
----
I tried to compile the debug version to get a better stack trace, but failed to get all dependencies installed from the debian unstable repository. The last error I had before I gave up was:
> Qt6TextToSpeech could not be found because dependency Qt6QmlIntegration could not be found.
It would be nice if the texttospeech integration was optional.

**Comment by JakubMelka** [comment]
Hello, I think it is similar problem as in #96 - it crashes in system dialog. Please try to download at least Qt 6.4, which has Qt6TextToSpeech.

**Comment by cweiske** [comment]
I am already using QT 6.4.2; your tool shows it so in the about dialog.

**Comment by JakubMelka** [comment]
@cweiske , what system do you use?

**Comment by cweiske** [comment]
With version 1.3.6, I can add .png images but still no .jpg images. I get a crash when adding a .jpg file via Menu > Insert > Insert Image. Happened with 5 different .jpg files.

The stacktrace is still as unhelpful as before:
```
(gdb) bt full
#0  ____longjmp_chk () at ../sysdeps/unix/sysv/linux/x86_64/____longjmp_chk.S:168
#1  0x65333004c4f6dd5e in  ()
```

**Comment by JakubMelka** [comment]
@cweiske, I have released a new version. Please try to use flatpak to install it. Did it help?

**Comment by cweiske** [comment]
Still crashes:
```
$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=Pdf4QtDocPageOrganizer io.github.JakubMelka.Pdf4qt
Gtk-Message: 12:15:47.997: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
qt.gui.imageio.jpeg: Wrong JPEG library version: library is 90, caller expects 62
```

**Comment by JakubMelka** [comment]
@cweiske, could you please try AppImage version?

**Comment by cweiske** [comment]
The AppImage download at https://github.com/JakubMelka/PDF4QT/releases/tag/v1.3.7 only has `
PDF4QT_Viewer_Profi-0629a71-x86_64.AppImage`, which is the PDF viewer. This bug is about the Doc Page Organizer.

How can I start the doc page organizer from the appimage? `--help` does not tell me how.

**Comment by JakubMelka** [comment]
@cweiske, try build from https://github.com/JakubMelka/PDF4QT/actions/runs/8348750839

**Comment by cweiske** [comment]
The issue is gone with PDF4QT PageMaster 1.3.7 on the AppImage.
