### ISSUE TITLE
Warning - Hardware acceleration is not supported on this device

### ISSUE THREAD

**Issue by fraterlinux** [JakubMelka/PDF4QT#106]
I use MX-23 (Debian 12). I installed the deb package. When I open PDF4QT it shows the following warning:

> Hardware acceleration is not supported on this device. OpenGL version at least 3.2 is required. Software rendering is used instead. Available OpenGL is 3.3 (Compatibility Profile) Mesa 22.3.6 using Mesa Intel(R) HD Graphics 2000 (SNB GT1). You can turn off hardware acceleration in 'Tools' menu using 'Options' item to stop displaying this message

See:
`$ glxinfo | grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 3.3
    Max compat profile version: 3.3
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL core profile version string: 3.3 (Core Profile) Mesa 22.3.6
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.3 (Compatibility Profile) Mesa 22.3.6
OpenGL shading language version string: 3.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 22.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
`

Is the warning correct?

**Comment by JakubMelka** [comment]
Hello, you are correct. There was an issue with version recognition. It has been resolved now.
