### ISSUE TITLE
Add scanned pdf conversion to bitonal [enhancement]

### ISSUE THREAD

**Issue by fraterlinux** [JakubMelka/PDF4QT#107]
A very important feature for a FOSS pdf editor is aggressive conversion of a color pdf to bitonal.

Many old books when scanned have yellowed pages and become heavy. A professional PDF application makes small bitonal PDFs like the books on this site:

https://www.forgottenbooks.com/en

I have to do a lot of juggling in Linux to be able to convert a color PDF to bitonal.

**Comment by JakubMelka** [comment]
Hello @fraterlinux, could you please provide some source PDF, which should be converted to bitonal?

**Comment by fraterlinux** [comment]
Old book scanned in color PDF format:
https://archive.org/download/MethodsOfKnowledgeSwamiSatprakashananda/Methods%20Of%20Knowledge%20%20-%20Swami%20Satprakashananda.pdf

Example of a PDF book scanned (converted) aggressive bitonal:
https://archive.org/download/manualzilla-id-6110080/6110080.pdf

Aggressive Bitonal reduces book size by approximately 90%.

**Comment by JakubMelka** [comment]
Hello,

I have implemented the feature, which includes two modes: automatic and manual. The automatic mode determines the threshold for black/white color using Otsu's 1D method. In the manual mode, you have the ability to select the threshold manually.

Could you please take some time to test it? You can locate it in the 'Edit' menu.

Best regards,
Jakub

![image](https://github.com/JakubMelka/PDF4QT/assets/11367048/80d3cf98-84a2-4912-97c0-e782dccefb2d)

**Comment by fraterlinux** [comment]
> Hello,
> 
> I have implemented the feature, which includes two modes: automatic and manual. The automatic mode determines the threshold for black/white color using Otsu's 1D method. In the manual mode, you have the ability to select the threshold manually.
> 
> Could you please take some time to test it? You can locate it in the 'Edit' menu.
> 
> Best regards, Jakub
> 
> ![image](https://user-images.githubusercontent.com/11367048/283849223-80d3cf98-84a2-4912-97c0-e782dccefb2d.png)

How do I download the binaries in Win and Lin to test?

**Comment by JakubMelka** [comment]
Currently, the feature is only available in the upstream. However, I am intending to create a new release in December. Until then, I would highly recommend building it from the source. Thank you for your understanding and patience.

**Comment by fraterlinux** [comment]
> Currently, the feature is only available in the upstream. However, I am intending to create a new release in December. Until then, I would highly recommend building it from the source. Thank you for your understanding and patience.

Don't worry. I understand and thank you for the excellent work with PDF4QT.

**Comment by fraterlinux** [comment]
I tested (1.3.6) and is working well.
