### ISSUE TITLE
PDF4QT Version 1.3.6 `GLIBC_2.38' not found

### ISSUE THREAD

**Issue by fraterlinux** [JakubMelka/PDF4QT#111]
I installed the Deb package on stable Debian (12)

When trying to execute
`$ Pdf4QtViewerProfi 
Pdf4QtViewerProfi: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /usr/bin/../lib/libPdf4QtLib.so.1.3.6)
Pdf4QtViewerProfi: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /usr/bin/../lib/libPdf4QtLib.so.1.3.6)
`
I had to downgrade to 1.3.5
I would like to request that binaries be provided that are compatible with Debian 12. The ideal for a foss application is that it was agnostic about libraries and could be used on any Linux distro. A Windows user uses the same version for 10 years and applications are still compatible. Windows users often buy paid PDF editors. Those who need a free PDF editor are Linux users!
I am a linux domestic user and I need stability. I have already tested some distros rolling-release, but they give a lot of maintenance. Always have edges to trim. 

I apologize for the outburst.

**Comment by JakubMelka** [comment]
Greetings @fraterlinux ,

I am disappointed to find that the program is incompatible with Debian. However, I would like to remind you that this is an open-source project and I am not paid support. My knowledge of Linux is quite limited. There was a request to create a .deb package installation (primarily for Ubuntu), and I have done so. As you have mentioned, I am primarily a Windows programmer and the issues you are facing are indeed unfamiliar to me on the Windows platform.

I am unsure how to make the program independent of the Linux distribution. It has multiple dependencies that need to be met.

What I would recommend is compiling the project yourself. It is a straightforward process and the README file provides instructions on how to do so. You would need to download VCPKG and Qt, a compiler, and then enter a few commands into the command line. By doing this, you can create your own installation on Debian, which will certainly work on that system.

Best regards,
Jakub

**Comment by fraterlinux** [comment]
How sad... 😢 😭

**Comment by JakubMelka** [comment]
Hello @fraterlinux,

I'm pleased to inform you that I've successfully installed Debian 12 on a VirtualBox VM, compiled the source code, and prepared the package. The release of version 1.3.6 has now been updated accordingly. I invite you to download the new version and give it a try.

However, please note that there are over 100+ Linux distributions, and it's not feasible for me to ensure compatibility with each one. I'm hopeful that this update will work across many of them, but I cannot guarantee it for all. Your feedback after testing on your distribution will be greatly appreciated.

Best regards,
Jakub

**Comment by fraterlinux** [comment]
Debian is the second oldest distro. Ubuntu is derived from Debian. Being compatible with stable Debian is a great achievement!

Thank you very much!!!
