### ISSUE TITLE
smooth scrolling

### ISSUE THREAD

**Issue by tomasmark79** [JakubMelka/PDF4QT#112]
Hello,

I want to ask if is (or will) possible smooth scrolling under Windows. It is very missing feature for learning from the PDF books.

Thank you.

**Comment by JakubMelka** [comment]
Hello @tomasmark79, that seems like an excellent feature! Could you please share some examples of applications that have this feature? I'm interested in seeing how it operates in practice. Thank you!

**Comment by tomasmark79** [comment]
Hello Jakube,
it is general mouse scroll with smooth movement of the document content. Not the jumping about around one centimeter, but smooth scroll with the middle button of the mouse.

**Comment by JakubMelka** [comment]
Hello,

Smooth scrolling for PDF viewing is now available. This feature should make reading PDFs more pleasant. Update to the latest version to try it out.
If there are any problems or additional feedback, please open a new issue.

Issue closed as resolved.
