### ISSUE TITLE
Color | Custom (green/black) partially works in scanned PDF (1.3.6)

### ISSUE THREAD

**Issue by fraterlinux** [JakubMelka/PDF4QT#113]
Some scanned PDF are totally black. 

Others the background remains white, only the bottom of the letter changes to black.

https://i.imgur.com/ereJ6Cz.png

**Comment by JakubMelka** [comment]
@fraterlinux , could you please provide some sample document?

**Comment by fraterlinux** [comment]
> @fraterlinux , could you please provide some sample document?

Correct file:
https://doceru.com/doc/nsncnv5

**Comment by JakubMelka** [comment]
Thank you for bringing this to my attention. The issue with the custom color feature on scanned PDFs has been addressed.
