### ISSUE TITLE
Improve search bar

### ISSUE THREAD

**Issue by raffaem** [JakubMelka/PDF4QT#116]
1. The search bar does not remember the previously typed search
2. The PDF is not scrollable while the search bar is open
3. if the zoom is too high, you will be redirected to the beginning of the page, instead of the location of the page where the term is found

**Comment by JakubMelka** [comment]
Hello @raffaem ,

The issue has been resolved. The search bar now retains the previous search text and settings. Additionally, the PDF scrolling functionality has been improved. When navigating through search results at a high zoom level, the view now correctly jumps to the appropriate text position.

Please let me know if you encounter any further problems.

Thank you for your patience.

**Comment by JakubMelka** [comment]
Hello @raffaem , could you please write a new issue?
