### ISSUE TITLE
Build from source fails

### ISSUE THREAD

**Issue by ddonevski** [JakubMelka/PDF4QT#117]
Hi, I tried to build PDF4QT from source on Linux Mint v21.2, but I am obviously doing something wrong. Following the instructions from [7. COMPILING](https://github.com/JakubMelka/PDF4QT#7-compiling), I set up VCPGK and installed all the packages listed in [4. THIRD PARTY LIBRARIES](https://github.com/JakubMelka/PDF4QT#4-third-party-libraries) using $VCPKG_ROOT/vcpkg install [library]. I looked up library names in [VCPKG list of packages](https://vcpkg.io/en/packages). To install Qt, I had to install a bunch of system packages from [Qt's list of dependencies](https://doc.qt.io/qt-6/linux-requirements.html).
Then I cloned PDF4QT, set it as working directory and ran configuration using the following line:

cmake -B build -S . -DPDF4QT_INSTALL_QT_DEPENDENCIES=1 -DPDF4QT_INSTALL_DEPENDENCIES=1  -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX='/'

I modified the original line from instuctions and added -DPDF4QT_INSTALL_QT_DEPENDENCIES=1 
-DPDF4QT_INSTALL_DEPENDENCIES=1 options because I wanted the project to contain all dependencies. I'm not even sure that "1" is a valid value because I coldn't find detailed descriptions of those variables. I got the following output:

-- Running vcpkg install
Detecting compiler hash for triplet x64-linux...
The following packages will be built and installed:
  * brotli:x64-linux -> 1.1.0#1
  * bzip2[core,tool]:x64-linux -> 1.0.8#5
    freetype[brotli,bzip2,core,png,zlib]:x64-linux -> 2.12.1#4
    ijg-libjpeg:x64-linux -> 9e#1
    lcms:x64-linux -> 2.14
    libpng:x64-linux -> 1.6.40
    openjpeg:x64-linux -> 2.5.0#1
    openssl:x64-linux -> 3.1.4#1
    tbb:x64-linux -> 2021.11.0
  * vcpkg-cmake:x64-linux -> 2023-05-04
  * vcpkg-cmake-config:x64-linux -> 2022-02-06#1
  * vcpkg-cmake-get-vars:x64-linux -> 2023-03-02
    zlib:x64-linux -> 1.3
Additional packages (*) will be modified to complete this operation.
Restored 12 package(s) from /home/davor/.cache/vcpkg/archives in 316 ms. Use --debug to see more details.
Installing 1/13 vcpkg-cmake:x64-linux...
Elapsed time to handle vcpkg-cmake:x64-linux: 475 us
Installing 2/13 zlib:x64-linux...
Elapsed time to handle zlib:x64-linux: 633 us
Installing 3/13 vcpkg-cmake-config:x64-linux...
Elapsed time to handle vcpkg-cmake-config:x64-linux: 345 us
Installing 4/13 libpng:x64-linux...
Elapsed time to handle libpng:x64-linux: 733 us
Installing 5/13 bzip2:x64-linux...
Elapsed time to handle bzip2:x64-linux: 694 us
Installing 6/13 brotli:x64-linux...
Elapsed time to handle brotli:x64-linux: 811 us
Installing 7/13 freetype:x64-linux...
Elapsed time to handle freetype:x64-linux: 1.58 ms
Installing 8/13 ijg-libjpeg:x64-linux...
Elapsed time to handle ijg-libjpeg:x64-linux: 561 us
Installing 9/13 lcms:x64-linux...
Elapsed time to handle lcms:x64-linux: 663 us
Installing 10/13 openjpeg:x64-linux...
Elapsed time to handle openjpeg:x64-linux: 669 us
Installing 11/13 vcpkg-cmake-get-vars:x64-linux...
Elapsed time to handle vcpkg-cmake-get-vars:x64-linux: 511 us
Installing 12/13 openssl:x64-linux...
Elapsed time to handle openssl:x64-linux: 2.47 ms
Installing 13/13 tbb:x64-linux...
Building tbb:x64-linux...
-- Downloading https://github.com/oneapi-src/oneTBB/archive/v2021.11.0.tar.gz -> oneapi-src-oneTBB-v2021.11.0.tar.gz...
-- Extracting source /media/davor/e57f40fb-a0dd-4f1d-a4c6-27b3c310b9a3/vcpkg/downloads/oneapi-src-oneTBB-v2021.11.0.tar.gz
-- Using source at /media/davor/e57f40fb-a0dd-4f1d-a4c6-27b3c310b9a3/vcpkg/buildtrees/tbb/src/v2021.11.0-0163f51d5f.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Fixing pkgconfig file: /media/davor/e57f40fb-a0dd-4f1d-a4c6-27b3c310b9a3/vcpkg/packages/tbb_x64-linux/lib/pkgconfig/tbb.pc
-- Fixing pkgconfig file: /media/davor/e57f40fb-a0dd-4f1d-a4c6-27b3c310b9a3/vcpkg/packages/tbb_x64-linux/debug/lib/pkgconfig/tbb.pc
-- Installing: /media/davor/e57f40fb-a0dd-4f1d-a4c6-27b3c310b9a3/vcpkg/packages/tbb_x64-linux/share/tbb/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 718 ms.
Elapsed time to handle tbb:x64-linux: 20 s
Total install time: 20 s
The package zlib is compatible with built-in CMake targets:

    find_package(ZLIB REQUIRED)
    target_link_libraries(main PRIVATE ZLIB::ZLIB)

The package libpng is compatible with built-in CMake targets:

    find_package(PNG REQUIRED)
    target_link_libraries(main PRIVATE PNG::PNG)

freetype is compatible with built-in CMake targets:

    find_package(Freetype REQUIRED)
    target_link_libraries(main PRIVATE Freetype::Freetype) # since CMake 3.10

The package lcms provides CMake targets:

    find_package(lcms2 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE lcms2::lcms2)

openjpeg provides CMake targets:

  \# this is heuristically generated, and may not be correct
  find_package(OpenJPEG CONFIG REQUIRED)
  target_link_libraries(main PRIVATE openjp2)

The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)

tbb provides CMake targets:

  \# this is heuristically generated, and may not be correct
  find_package(TBB CONFIG REQUIRED)
  target_link_libraries(main PRIVATE TBB::tbb TBB::tbbmalloc)

-- Running vcpkg install - done
-- The CXX compiler identification is GNU 11.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found WrapOpenGL: TRUE  
-- Found XKB: /usr/lib/x86_64-linux-gnu/libxkbcommon.so (found suitable version "1.4.0", minimum required is "0.5.0") 
-- Could NOT find WrapVulkanHeaders (missing: Vulkan_INCLUDE_DIR) 
-- Could NOT find Qt6Svg (missing: Qt6Svg_DIR)
-- Could NOT find Qt6TextToSpeech (missing: Qt6TextToSpeech_DIR)
-- Could NOT find WrapVulkanHeaders (missing: Vulkan_INCLUDE_DIR) 
-- Could NOT find Qt6Multimedia (missing: Qt6Multimedia_DIR)
CMake Error at /media/davor/e57f40fb-a0dd-4f1d-a4c6-27b3c310b9a3/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt component "Svg".

  Expected Config file at
  "/usr/lib/x86_64-linux-gnu/cmake/Qt6Svg/Qt6SvgConfig.cmake" does NOT exist

  Failed to find Qt component "TextToSpeech".

  Expected Config file at
  "/usr/lib/x86_64-linux-gnu/cmake/Qt6TextToSpeech/Qt6TextToSpeechConfig.cmake"
  does NOT exist

  Failed to find Qt component "Multimedia".

  Expected Config file at
  "/usr/lib/x86_64-linux-gnu/cmake/Qt6Multimedia/Qt6MultimediaConfig.cmake"
  does NOT exist

  

Call Stack (most recent call first):
  CMakeLists.txt:46 (find_package)

-- Configuring incomplete, errors occurred!
See also "/media/davor/e57f40fb-a0dd-4f1d-a4c6-27b3c310b9a3/PDF4QT/build/CMakeFiles/CMakeOutput.log".

I'm not familiar with VCPKG and what it is supposed to do. From what I see, it builds and install a bunch of packages which I already installed earlier and which are all present in vcpkg/packages. Then CMAKE jumps in and starts complaining that it can't find Qt makefiles and components in system directories. Of course it can't, they're all installed within vcpkg folder. I expected that when I install packages using VCPKG package manager and then run the config with VCPKG, it would provide all the packages installed inside it. But this obviously doesn't happen. Can anyone please tell me what is it that I'm doing wrong and how is this supposed to work? Thanks.

**Comment by sheecegardezi** [comment]
@ddonevski were you able to resolve the issue? I am still getting the error:
```

  Expected Config file at
  "/usr/lib/x86_64-linux-gnu/cmake/Qt6TextToSpeech/Qt6TextToSpeechConfig.cmake"
  does NOT exist

```

**Comment by sheecegardezi** [comment]
change the contents of vcpkg.json too:
 
```

{
  "name": "pdf4qt",
  "version-string": "1.3.7",
  "dependencies": [ "tbb", "openssl", "lcms", "zlib", "openjpeg", "freetype", "ijg-libjpeg", "libpng", "blend2d", "qt" ]
}
```

**Comment by ddonevski** [comment]
@sheecegardezi hi, it's been a while since I did it, but I made notes in Croatian language so here's Google translate from Croatian:

Follow the installation instructions from GITHub:
https://github.com/JakubMelka/PDF4QT

The Qt Installer is available at:
https://www.qt.io
In the upper right corner of the page is "Download. Try." button.
Select the open source option from the page opened by clicking on "Download. Try."
Download the installer by logging in with my Gmail account. 

List of dependencies:
https://doc.qt.io/qt-6/linux-requirements.html

OpenGL also needed for compilation maybe:
sudo apt-get install libgl1-mesa-dev

It is necessary to add the directory 'overlays' to the project directory and set the overlay for libpng in order to link the build with the system libpng package. If left to vcpkg, it pulls its own libpng so the app crashes when trying to load png icons when the file dialog is opened.
Overlay settings as instructed: https://devblogs.microsoft.com/cppblog/using-system-package-manager-dependencies-with-vcpkg/
Checking system version: dpkg -l | grep png to write the appropriate version to the .json overlay configuration.

Configure:
cmake -B build -S . -DVCPKG_OVERLAY_PORTS='/media/davor/e57f40fb-a0dd-4f1d-a4c6-27b3c310b9a3/PDF4QT/overlays' -DPDF4QT_INSTALL_QT_DEPENDENCIES=0 -DPDF4QT_QT_ROOT='/home/davor/Qt/6.6.1/' -DCMAKE_PREFIX_PATH='/home/ davor/Qt/6.6.1/gcc_64/lib/cmake/' -DCMAKE_MODULE_PATH='/home/davor/Qt/6.6.1/gcc_64/lib/cmake/' -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake/' -DCMAKE_INSTALL_PREFIX='/'

After the build and installation, before starting, add the path to the libraries:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/davor/Qt/6.6.1/gcc_64/lib/

As you can see, I had to download Qt because my OS didn't have the required libraries (Text2speech being one of them)
