### ISSUE TITLE
Adding CMAKE options for minimal builds?

### ISSUE THREAD

**Issue by nyalldawson** [JakubMelka/PDF4QT#118]
Hi there!

I'm really keen to use your library as it's the only solution I can find which permits vector based PDF -> QPainter rendering. :+1: 

I'm wondering if you would be willing to accept patches to allow minimal builds of the Pdf4QtLib library, eg via cmake switches to disable OpenGL support. Is this something you're interested in external contributions for?

**Comment by JakubMelka** [comment]
Hello @nyalldawson, contribution requires to sign CLA. However, you just need to disable OpenGL support via CMAKE switch?

**Comment by nyalldawson** [comment]
No problem, I'm happy to sign the agreement!

At this stage I'm just trying to determine if adding switches like this would be acceptable to you, or if you'd prefer not to introduce these in your code base...?

**Comment by JakubMelka** [comment]
Hello @nyalldawson,

I've introduced a new CMAKE option in the project to control the usage of OpenGL. When this option is set to OFF, the project is configured without any OpenGL dependencies, effectively eliminating the use of OpenGL within the codebase. This should provide more flexibility for environments where OpenGL is not available or its usage is not desired.

Please let me know if this solution meets your requirements or if there are any further adjustments needed.

Best regards.

**Comment by JakubMelka** [comment]
I will attempt to handle it myself. Unfortunately, this necessitates significant modifications in the code, which must be handled with great care.

**Comment by JakubMelka** [comment]
Splitting the libraries is finished. The core library does not have a dependency on QWidgets. Closed as finished. Please reopen if you find any problems.
