### ISSUE TITLE
Improve search bar 2 (the revenge)

### ISSUE THREAD

**Issue by raffaem** [JakubMelka/PDF4QT#119]
1. The first time you open the Search dialog, it says "indexing content", and then the dialog disappears.  
2. Pressing  Enter/Return within the text box of the search bar seems to go to the last entry found. But it should go to the next one, it should behave like the "Next" button.

**Comment by JakubMelka** [comment]
The problem of the Search dialog closing unexpectedly during initial indexing has been resolved. Additionally, the functionality of the Enter/Return key in the search bar has been adjusted to navigate to the first result. You can move to the next result using the F3 key and to the previous result using the Shift+F3 key.
