### ISSUE TITLE
Is dynamic XFA forms planned?

### ISSUE THREAD

**Issue by jointri** [JakubMelka/PDF4QT#12]
Thanks for implementing static XFA support. Is there any plans for dynamic XFA PDFs which is the other kind of XFA PDF you can receive?

**Comment by JakubMelka** [comment]
Hello,

The problem with dynamic XFA forms is, that specification has 1600 pages, and is even larger than PDF specification itself. Moreover, in newest PDF specification, XFA is deprecated. To implement it fully, it can take several years of work. What kind of document do you need to process?

I am now focusing to cover features of commercial programs, which are easier to implement - for example, I am now doing electronic / digital signatures (create graphics of signature using tools and then sign document using certificate).

**Comment by JakubMelka** [comment]
I have decided that I will not support dynamic XFA forms. It is out of scope of this project and XFA is deprecated in new PDF.
