### ISSUE TITLE
Run Error on Windows x64

### ISSUE THREAD

**Issue by xlance-github** [JakubMelka/PDF4QT#122]
All PDF4QT executables cause an 0xc0000005 error on launch (*. msi and *.zip versions)

![Error](https://github.com/JakubMelka/PDF4QT/assets/74504527/8661face-70f4-4799-bdaf-e7c8522f3cc8)

**Comment by JakubMelka** [comment]
Hello @xlance-github , could you please tell me version of the operating system (Windows 10 or Windows 11) and version of PDF4QT?

**Comment by xlance-github** [comment]
Windows 7 x64
PDF4QT 1.3.6

**Comment by JakubMelka** [comment]
@xlance-github : Unfortunately, Qt6 does not support Windows 7. See this: https://www.qt.io/blog/qt6-development-hosts-and-targets
