### ISSUE TITLE
Alternative software rendering backend

### ISSUE THREAD

**Issue by daljit97** [JakubMelka/PDF4QT#123]
This is just a suggestion, but I think it would be cool if this project could use a faster rendering software backend. In particular, QPainter is rather slow and old. For example, using a 2D rendering library like [Blend2D](https://blend2d.com/), which is likely to be one of the fastest 2D software renderers out there, the software rendering should be significantly faster. Skia is another option, but it is a huge dependency and probably not worth it.
In fact, in theory it should be possible to provide a custom `QPaintEngine` and just continue using the `QPainter` APIs with an alternative backend.

**Comment by JakubMelka** [comment]
@daljit97  Very good idea!  I will give it a high priority.

**Comment by JakubMelka** [comment]
Hello @daljit97, I have successfully added Blend2D rendering engine to my project. Please try it.
