### ISSUE TITLE
Cannot Install on popOS

### ISSUE THREAD

**Issue by defencedog** [JakubMelka/PDF4QT#127]
Dependency error : Libqt6texttospeech6

Linux pop-os 6.6.6-76060606-generic #202312111032~1702306143~22.04~d28ffec SMP PREEMPT_DYNAMIC Mon D x86_64 x86_64 x86_64 GNU/Linux

**Comment by JakubMelka** [comment]
Hello @defencedog, did you try flatpak version?

**Comment by defencedog** [comment]
No regular `deb` package

**Comment by JakubMelka** [comment]
@defencedog , could you please try a Flatpak version? https://flathub.org/apps/io.github.JakubMelka.Pdf4qt

**Comment by JakubMelka** [comment]
@defencedog, I have also prepared AppImage. Workaround exists - closing as solved.
