### ISSUE TITLE
Can this program have redaction and sanitization capabilities?

### ISSUE THREAD

**Issue by jointri** [JakubMelka/PDF4QT#13]
I feel like something that's missing from this program is ability to redact (permanently remove and cover with black) images and/or text along with ability to sanitize the document for anything personal. Adobe Acrobat will remove ALL annotations along with any potential personal info and strip out any javascript making it safe to share with someone else when sanitizing a PDF. Could you consider implementing that? Thanks. Also, I'm very pleased to witness that your PDF reader actually removes annotations rather than keeping them in like poppler and mupdf do. I'll definitely recommend this program if anyone talks about PDF readers.

**Comment by JakubMelka** [comment]
Hello,
I am happy you are interested in my software. Redaction is already implemented in "Redact" plugin. Redact plugin can remove text and image content (and redacted content is covered in black). To turn on Redact plugin, go to Options, section Plugins and check the Redact plugin. See image:
![obrazek](https://user-images.githubusercontent.com/11367048/170837416-ebf43f79-ab54-496c-b7fd-0e38d1b11ef8.png)

Redact also sanitizes document (it should remove all annotations / javascript). However, I would like to implement sanitization of the document without redacting it.

**Comment by jointri** [comment]
@JakubMelka 
Awesome man. If I may ask another question since I rather not make a new thread, are you going to implement being able to extract pages/move pages around/delete pages/add new pages?

**Comment by JakubMelka** [comment]
This is implemented in separate application - PDF4QT DocPage Organizer. It allows you (among other things) to extract/move/delete/add pages of the PDF document. Also, several PDF documents can be merged into single one, or perform inverse operation: to split single PDF document into several PDF documents.

Small introduction: DocPage Organizer works with workspace containing page groups. When you add document to the workspace, one single page group of whole document pages is being created. You can split this group to single pages, extract/delete/add pages, and move pages via drag and drop.

Then, you can perform three different actions to produce new PDF documents via menu "Make":
- Unite all page groups into single document (key F5)
- Separate to multiple documents (key F6) - produces single document per page
- Separate to multiple documents grouped (key F7) - produces single document per page group (so for each page group, one single document is being created containing all pages of the page group)

See sample screenshot with two documents, single page and image:
![obrazek](https://user-images.githubusercontent.com/11367048/170867446-83b8d1a1-c0f3-438a-aedb-7167a9aeb41d.png)

**Comment by jointri** [comment]
Can I extract text and images from a page using DocPage Organizer @JakubMelka ?

**Comment by JakubMelka** [comment]
DocPage Organizer is basically a multiple document page manipulator, it works only with pages. However, to extract text / images, run Viewer Profi, and there you will find two tools. One starts tool with text selection (and you can extract text via Ctrl+C), the other tool copies image to clipboard via click on image. Both tools respect DRM settings of the document, so to perform this extraction, you must have appropriate rights. Also, you can take screenshot of the page.

You can use these icons:
![obrazek](https://user-images.githubusercontent.com/11367048/170868693-c179706d-cad9-4318-a285-4f3299688a90.png)

Alternatively, you can use pdftool, which has two commands to extract content:
- pdftool fetch-text mydocument.pdf
- pdftool fetch-images mydocument.pdf

**Comment by JakubMelka** [comment]
I think I can close this issue, as requested functionality is implemented.
