### ISSUE TITLE
Difference between outline and bookmarks

### ISSUE THREAD

**Issue by raffaem** [JakubMelka/PDF4QT#131]
I  don't get the difference between outline and bookmarks.

After opening my PDF, "Bookmarks" contain the first level of the bookmarks defined in "Outline".

**Comment by JakubMelka** [comment]
Hello @raffaem,

Bookmarks are somewhat different than outlines. An outline is the content defined in a PDF by the author of the PDF, whereas bookmarks can be created by the user while browsing. A user can navigate to a certain page, press Ctrl+M, and it will be automatically added to the bookmarks. You can navigate between bookmarks using the keys 'Ctrl+,' (previous bookmark) and 'Ctrl+' (next bookmark). I have also incorporated the ability to export and import bookmarks, in case a user wishes to save their bookmarks.

So,
 - The outline is permanently defined in the PDF document (although it can be edited in my software)
 - Bookmarks are user-defined marked pages, between which you can easily navigate.
 - First level of outline is automatically added to the bookmarks, if it is turned on.
