### ISSUE TITLE
PDF diff hangs

### ISSUE THREAD

**Issue by raffaem** [JakubMelka/PDF4QT#132]
I have two PDF files of more than 1k pages each.

1.  Opening one of them  with PDF Diff doesn't load it automatically in the left pane
2. When I open both of them with the toolbar buttons and click "Compare", PDF4QT Diff hangs and freezes.

**Comment by JakubMelka** [comment]
Hello @raffaem , could you please provide the problematic PDF documents? Or at least similar ones?

**Comment by raffaem** [comment]
I sent you an email

**Comment by JakubMelka** [comment]
Hello, yes, I will answer, but I am very busy now - it's holidays.

**Comment by JakubMelka** [comment]
Hello @raffaem , could you please send me problematic PDFs?

**Comment by raffaem** [comment]
> Hello @raffaem , could you please send me problematic PDFs?

Hello,

sorry, they are protected by copyright.

I will reopen it if I'm able to reproduce it with free documents.

Best,
