### ISSUE TITLE
Rectangle selector when choosing the page of the PDF

### ISSUE THREAD

**Issue by raffaem** [JakubMelka/PDF4QT#133]
When, in the outline menu, I right click on an item and choose Set Target -> Fit Page, I obtain a rectangle selector I don't understand the purpose of.

Isn't it sufficient to just click on the page?

**Comment by JakubMelka** [comment]
I used rectangle picking tool. I will adjust it.

**Comment by raffaem** [comment]
Can we have a "Current page" option?

My workflow is as follows: I read the PDF, then when I need to close it I save a bookmark indicating the last page I was reading before closing it.

**Comment by JakubMelka** [comment]
@raffaem, I have added the picking only page option, tomorrow, I will create option to save Current Page.

**Comment by JakubMelka** [comment]
@raffaem , now, last viewed page is remembered and restored, when file is opened.
