### ISSUE TITLE
Redaction - Cannot convert '#000000' to color value

### ISSUE THREAD

**Issue by msavli** [JakubMelka/PDF4QT#137]
On Win 10 I made with Pdf4QtViewerProfi.exe  ver 1.3.6  'Redact rectangle' on PDF document.
After creation of a rectangle, this rectangle can no be seen. As it was not there. But there is this rectangle:

![slika](https://github.com/JakubMelka/PDF4QT/assets/13658822/e8945e55-7738-484f-9ef6-aba5c76cdfbb)

If I tried to save with "Create redacted document" I got Cannot convert '#000000' to color value

![slika](https://github.com/JakubMelka/PDF4QT/assets/13658822/98813add-8b44-4771-afb3-6ced459f176d)

If I unchecked: "Fill redacted area with color" (because I can not otherwise save) I got rectangle that is not filled with color.

Saved dokument has a blank square.

![slika](https://github.com/JakubMelka/PDF4QT/assets/13658822/8a08d18e-fb6b-4b64-89d6-af161e3ed371)

But same procedure on other document create rectangles instead of redacted document

![slika](https://github.com/JakubMelka/PDF4QT/assets/13658822/49ed1e79-730b-49b3-b40b-065c46dced00)

**Comment by JakubMelka** [comment]
Hello @msavli,

I've resolved a number of issues in the redaction plugin:

- The rectangle tool was not visible as it was disabled by default.
- There was an error in the color conversion process.
- There was an issue with merging multiple rectangles properly.

All of these bugs have now been addressed. Please await the completion of the build (https://github.com/JakubMelka/PDF4QT/actions/runs/7349910214) and then give it a try!

Please reopen the issue, if you find some more bugs.
