### ISSUE TITLE
Changing page layout reset the current page

### ISSUE THREAD

**Issue by raffaem** [JakubMelka/PDF4QT#139]
1. Open the attached PDF with Profi
2. Go to page 11
3. Click View -> Page layout -> Continuous
4. You will be redirected to page 1

[Datatypes In SQLite.pdf](https://github.com/JakubMelka/PDF4QT/files/13797169/Datatypes.In.SQLite.pdf)

**Comment by JakubMelka** [comment]
Fixed.
