### ISSUE TITLE
New bookmarks created empty?

### ISSUE THREAD

**Issue by raffaem** [JakubMelka/PDF4QT#140]
1. Open a PDF
2. Go to a page > 1, e.g. page 10
3. In the Sidebar -> Outline, create new item
4. Close the PDF
5. Open the PDF
6. Go to page 1
7. Click on the item you created in the side bar
8. Nothing happens

The exact same things happens if you open the PDF with other readers (e.g. Okular).

It looks like the newly created bookmark points to nothing until you right click -> Set Target.

It should point by default to the current page.

**Comment by JakubMelka** [comment]
Implemented.
