### ISSUE TITLE
Cannot reach the top

### ISSUE THREAD

**Issue by raffaem** [JakubMelka/PDF4QT#142]
When you are in "Single page" Page Layout, you go to the very first page of the PDF, and you scroll up with the touchpad or the mouse wheel, it kind of "scroll" to the bottom of the first page, instead of just doing nothing once the top of the first page is reached.

**Comment by JakubMelka** [comment]
Hello @raffaem , could you please attach some PDF, where it does?

**Comment by raffaem** [comment]
[Datatypes In SQLite.pdf](https://github.com/JakubMelka/PDF4QT/files/13800842/Datatypes.In.SQLite.pdf)

**Comment by JakubMelka** [comment]
Implemented.
