### ISSUE TITLE
Failed to run on Windows 8.1 - DirectX 12 dependency

### ISSUE THREAD

**Issue by Midi-In** [JakubMelka/PDF4QT#153]
The program won't run on Windows 8.1, as it's trying to load DirectX 12 libraries which are obviously nonexistent on Windows 8.1. Why on earth would a PDF editor need DX? Is that a Qt dependency? And most importantly - can this dependency be removed without affecting the programs functionality?

**Comment by JakubMelka** [comment]
@Midi-In , hello Qt 6 does not support and will not run on Windows 8.1.
https://doc.qt.io/qt-6/supported-platforms.html
