### ISSUE TITLE
Split Page

### ISSUE THREAD

**Issue by digitarenet** [JakubMelka/PDF4QT#156]
Is it possible to split an existing PDF in separate file (from page X to Y for example)?

**Comment by JakubMelka** [comment]
Hello @digitarenet, yes, to begin, simply launch PDF4QT DocPage Organizer and open the PDF file. Next, organize the pages into the groups that you want to separate. Once that's done, press F7 or select "Separate to Multiple Documents (Grouped)" and the program will generate a set of PDF files containing the specified pages.
