### ISSUE TITLE
1.3.7 debian .deb release

### ISSUE THREAD

**Issue by 2CLC** [JakubMelka/PDF4QT#157]
Hi @JakubMelka 
First let me thank you for a good job on the project.
It seems however, that the debs are missing from current release. Are you planning to compile .deb packages for 1.3.7?

**Comment by JakubMelka** [comment]
Hello @2CLC, I wish to, but Ubuntu/Debian does not have packages for Qt 6.6, so I am considering to use AppImage instead.

**Comment by 2CLC** [comment]
Hi. I see. Well, I understand the issue since QT is more than troublesome, especially on Free distributions like Debian.
Wish you used GTK instead :-)

Nevermind and thanks for your reply.

**Comment by JakubMelka** [comment]
@2CLC, could you please try AppImage from version 1.3.7? I have updated it now.

**Comment by fraterlinux** [comment]
> @2CLC, could you please try AppImage from version 1.3.7? I have updated it now.

In MX/Debian 12 the AppImage opens. But only PDF4QT Viewer Profi 1.3.7 runs. How do I switch between the other PDF4QT Viewer Lite, PDF4QT DocPage Organizer and PDF4QT DocDiff applications?

**Comment by 2CLC** [comment]
> @2CLC, could you please try AppImage from version 1.3.7? I have updated it now.

Apologies for late answer, I've got sick.
I've tested on Debian 12 Bookworm and it's working well, thank you.

However as @fraterlinux mentioned above, I'm missing the rest of important tools in both PageOrganizer and Diff apps.
I would appreciate if you compiled these apps as well.

**Comment by JakubMelka** [comment]
Yes, I am planning to do it after Blend2D rendering engine implementation.

**Comment by JakubMelka** [comment]
@2CLC: AppImage can now launch all applications.

**Comment by fraterlinux** [comment]
ubuntu-deb-package.zip doesn’t work in MX/Debian 12. 

A package for Debian 12 usually runs on Ubuntu, but not vice versa.

**Comment by JakubMelka** [comment]
@fraterlinux , yes, ubuntu deb package does not work. I will support only AppImage/FlatPak from now.
