### ISSUE TITLE
PDF4QT AppImage struggled with large file, and after closing, the system was slow to respond.

### ISSUE THREAD

**Issue by SnowballV** [JakubMelka/PDF4QT#158]
Thanks very much for offering the PDF4QT AppImage.
I tried PDF4QT_Viewer_Profi-0629a71-x86_64.AppImage on Kubuntu 22.04.3.
It looks to me as if the AppImage needs some additional work.
PDF4QT AppImage struggled to render a large 2.7 MiB 247-page PDF file. When I tried to browse the PDF from low to a high page numbers, the application didn't render the selected pages. There was no such issue with smaller PDF files, 571 KiB 19 pages.
Furthermore, after opening and closing some documents, making a few annotations for testing, and closing the application again, I noticed my Kubuntu system was very slow to respond. I checked Kubuntu System Monitor, to see if there were processes still taking up memory or CPU, but I think there weren't. To correct responsiveness, I rebooted the system.
I must say it's an old computer, rather low in resources, 4 GB RAM and an Intel Core2 Duo E8600, but a PDF viewer and editor like Okular works nicely on that system.
Hence, I suppose the PDF4QT AppImage needs some additional work.
Thanks very much, once more.

**Comment by SnowballV** [comment]
In addition to my original post -
I searched in issues for 'large': is:issue is:all large
I notice that in issue #102 it is mentioned that the implementation for processing PDF files "may require more memory due to its multi-threaded nature. In addition, I also use a cache for page images, which might further increase the memory usage."
If this is the same for the PDF4QT AppImage, that may be the reason for the issues that I experienced. Perhaps my 4 GB of RAM was not quite sufficient, and memory was allocated to swap space, making the system sluggish, even some time after closing the application.
If this is what happened, the PDF4QT AppImage may not be most suitable for large files on low-resource systems.

**Comment by JakubMelka** [comment]
Hello @SnowballV , could you please attach problematic PDF files?

**Comment by fraterlinux** [comment]
I opened a 742MB PDF in Chinese and it didn't crash PDF4QT Viewer Profi 1.3.7 (AppImage).

**Comment by SnowballV** [comment]
> Hello @SnowballV , could you please attach problematic PDF files?

It can be downloaded from this page:
https://richtlijnendatabase.nl/richtlijn/schildklierfunctiestoornissen
Select "Download richtlijn", next select "GENEREER".

**Comment by SnowballV** [comment]
> I opened a 742MB PDF in Chinese and it didn't crash PDF4QT Viewer Profi 1.3.7 (AppImage).

Did you browse the file from a couple of low page numbers to a few high page numbers and back again?
Did the application render all selected pages correctly?

And did you make a few annotations for testing, before closing the application?

If all works well for you, that's good.

What are your system specs, RAM and processor?
Is it better than my old low-resource system (4 GB RAM and an Intel Core2 Duo E8600)?
And what is your distro and DE, exactly?

Thanks very much.

**Comment by fraterlinux** [comment]
> > I opened a 742MB PDF in Chinese and it didn't crash PDF4QT Viewer Profi 1.3.7 (AppImage).
> 
> How many pages was the PDF file? Did you browse the file from a couple of low page numbers to a few high page numbers and back again? Did the application render all selected pages correctly?
> 
> And did you make a few annotations for testing, before closing the application?
> 
> If all works well for you, that's good.
> 
> What are your system specs, RAM and processor? Is it better than my old low-resource system (4 GB RAM and an Intel Core2 Duo E8600)? And what is your distro and DE, exactly?
> 
> Thanks very much.

Debian 12, i3(2gn), 8Gb ram, amd gpu.

**Comment by fraterlinux** [comment]
> > Hello @SnowballV , could you please attach problematic PDF files?
> 
> It can be downloaded from this page: https://richtlijnendatabase.nl/richtlijn/schildklierfunctiestoornissen Select "Download richtlijn", next select "GENEREER".
> 
> **Edit:** Ideally, I think you should best test on an (old) low-resource system like mine (4 GB RAM and Intel Core2 Duo E8600).

In this pdf Color | Custom (green/black) does not work. I'm going to open an issue!

**Comment by JakubMelka** [comment]
@SnowballV, I tried it on my on Ubuntu using VirtualBox, with 8 GB memory with i5 six core intel processor, everything worked and browsing is fast.

**Comment by SnowballV** [comment]
@JakubMelka,
Thank you for testing.

Last January, I tested the January 21 AppImage version.
Did you use that one, or the current daily build? I haven't tested the daily build.

Regarding system specs, your 8 GB memory is double of my 4 GB RAM, of course.
And you did not specify your i5, but depending on its specs, its performance may be much higher than my Intel Core2 Duo E8600.

**Comment by JakubMelka** [comment]
@SnowballV, please try newest AppImage from the daily build. However, if you have very old computer, I am afraid I cannot solve it.

**Comment by SnowballV** [comment]
@JakubMelka,
Thanks.
Exactly where do I find the AppImage daily build?
Is it this one? https://github.com/JakubMelka/PDF4QT/actions/runs/9681243851
If so, I will test later. Thanks again.

In case 4 GB of RAM is not sufficient to work with large files, and memory is allocated to swap space, making the system sluggish, PDF4QT may not be most suitable for large files on low-resource systems.

**Comment by JakubMelka** [comment]
Yes, it is that one. Well, I am afraid you should use at least moderate resource systems to open large PDF files. PDF4QT is pre-caching many data, so displaying them is fast.

**Comment by SnowballV** [comment]
Ah, OK, thanks, I will test later today, or this weekend.
I'll report back after that.

Regarding system resources, I anticipate my old system has insufficient RAM to work with PDF4QT and large files. If so, that's OK, it is good to be aware. In that case, I still have Okular, and I will try PDF4QT later when at some point I replaced my system.

**Comment by SnowballV** [comment]
I tested PDF4QT_LaunchPad-1e79871-x86_64.AppImage.
I tested the Viewer and the Editor.

The good news is that I did not encounter the issues that I had with PDF4QT_Viewer_Profi-0629a71-x86_64.AppImage, last January.
There was no rendering issue with the same 2.7 MiB 247-page PDF file that I used for testing last January, nor with other documents.
And after opening and closing some documents, making a few annotations for testing, and closing the application again, there was no issue with my system's responsiveness.
That is all good.

However, I noticed a new issue, which is outside the scope of the original issue report.
The new issue is that annotations do not show. Annotations do show in the Thumbnails bar, but not in the main window or field -- not in the Editor, and when the document is saved the annotations don't show in the Viewer either.
The annotations do show when I open the saved documents in Okular.

Do you have suggestions for debugging this new issue, annotations not showing?

**Comment by JakubMelka** [comment]
@SnowballV, yes, please close the issue and write new one. But please, check, if this setting is turned on:
![image](https://github.com/JakubMelka/PDF4QT/assets/11367048/b3eac66c-200c-4b04-8b08-dc71c7af66d7)

**Comment by SnowballV** [comment]
Closed, as the reported original issue in PDF4QT_Viewer_Profi-0629a71-x86_64.AppImage is resolved in daily build PDF4QT_LaunchPad-1e79871-x86_64.AppImage.
