### ISSUE TITLE
Offer 4 AppImage one for each App [enhancement]

### ISSUE THREAD

**Issue by fraterlinux** [JakubMelka/PDF4QT#159]
Offer 4 AppImage one for each App:

PDF4QT Viewer Profi
PDF4QT Viewer Lite
PDF4QT DocPage Organizer
PDF4QT DocDiff

Or a way to switch between Apps when running the AppImage.

**Comment by JakubMelka** [comment]
@fraterlinux, maybe AppImage runs some "Launch" application, which can launch these four applications?

**Comment by fraterlinux** [comment]
> @fraterlinux, maybe AppImage runs some "Launch" application, which can launch these four applications?

Yes or to follow Linux ethics, an AppImage for each of the 4 Apps compressed into a tar.gz to be downloaded.

**Comment by JakubMelka** [comment]
Hello @fraterlinux, please try AppImage from https://github.com/JakubMelka/PDF4QT/actions/runs/8332362007.

**Comment by JakubMelka** [comment]
I tested it on Linux MINT and it works.

**Comment by fraterlinux** [comment]
> Hello @fraterlinux, please try AppImage from https://github.com/JakubMelka/PDF4QT/actions/runs/8332362007.

AppImage works in MX/Debian 12
