### ISSUE TITLE
Compilation errors with recent OpenSSL versions

### ISSUE THREAD

**Issue by daljit97** [JakubMelka/PDF4QT#16]
Hi, I've been trying to build this library on Windows 11. I'm using CMake and vcpkg to manage the dependencies.
When I tried to compile the library using MSVC 2019, I get the following compilation error:

> sources\pdfsignaturehandler.cpp(1462,41): error C2440: 'initializing': cannot convert from 'const rsa_st *' to 'RSA *'

I think this is caused by a change in recent versions of OpenSSL 3 (I think [this one](https://github.com/openssl/openssl/commit/7bc0fdd3fd4535e06c35b92d71afab9a6de94cc5)), that `EVP_PKEY_get0*` functions have a const return type.

**Comment by JakubMelka** [comment]
Hello, I will have a look on it.

**Comment by JakubMelka** [comment]
Hello, I think I have managed to fix it - I do not use this function anymore. Please let me know, if it works.

**Comment by daljit97** [comment]
Hi, that seems to work. Thanks for the quick fix!

**Comment by JakubMelka** [comment]
OK, I will close it as resolved.
