### ISSUE TITLE
Unable to render probably valid PDF

### ISSUE THREAD

**Issue by finn-cz** [JakubMelka/PDF4QT#163]
In version 1.3.7, I'm unable to open this datasheet:

https://ww1.microchip.com/downloads/aemDocuments/documents/APID/ProductDocuments/DataSheets/MCP23017-Data-Sheet-DS20001952.pdf

Opening fails with _Document read error: Expected 48 characters long string in entry 'O'. Provided length is 127._

My presumption about the validity of the PDF is based only on the fact that Adobe Reader or SumatraPDF open the file without complaint.

**Comment by JakubMelka** [comment]
Now, it can be opened. However, the PDF itself is not correct; it generates an invalid key of length 127. The correct length should be 48 bytes. If I adjust these bytes to a length of 48, it can be opened. My validation was overly stringent.
