### ISSUE TITLE
Taskbar icon not shown in linux mint.

### ISSUE THREAD

**Issue by ritulahkar** [JakubMelka/PDF4QT#164]
When launching the latest appimage 1.3.7, only a generic icon is shown as shown in the image. I am using Linux mint 21.3.

![Screenshot from 2024-02-09 10-44-11](https://github.com/JakubMelka/PDF4QT/assets/105012118/c2bab29e-e4f7-4b87-b7b4-44b61f62c1a5)

**Comment by ritulahkar** [comment]
May be this can be of some help:

https://discourse.appimage.org/t/appimage-does-not-show-icon-in-task-bar/40/2

**Comment by JakubMelka** [comment]
Hello, it seems to be working now. Try https://github.com/JakubMelka/PDF4QT/actions/runs/8101084553 .
