### ISSUE TITLE
Insert > Inline Text   latency issues on Flatpak and Appimage packages 

### ISSUE THREAD

**Issue by TriggerDingus** [JakubMelka/PDF4QT#165]
I'm really enjoying PDF4QT. It's been difficult to find a feature-rich PDF editor and this tool is delivering the goods!

One issue I have is that when inserting inline text, there is considerable latency in the "crosshair" tool that comes up. Trying to use this placement tool is difficult because of this latency between my mouse and the online crosshairs. It literally takes 1-2 seconds for the crosshairs to catch up with the movement of my mouse.

Thinking this might be an issue with the flatpak version of the app, I tried the appimage and experienced the same latency.

I'm running a fairly robust 12-core i7 and it's twiddling it's thumbs when running the app, so I don't believe the problem is in my system.

**Comment by JakubMelka** [comment]
Hello @TriggerDingus, does it appear on some special PDF, or could you please post the PDF here, if it is available?

**Comment by TriggerDingus** [comment]
> Hello @TriggerDingus, does it appear on some special PDF, or could you please post the PDF here, if it is available?

[2023 MSC Tax Schedule Organizer (blank template).pdf](https://github.com/JakubMelka/PDF4QT/files/14251836/2023.MSC.Tax.Schedule.Organizer.blank.template.pdf)

**Comment by JakubMelka** [comment]
@TriggerDingus, I tried it on MS Windows and it works fast to add inline text to this PDF. What system do you have?

**Comment by TriggerDingus** [comment]
> @TriggerDingus, I tried it on MS Windows and it works fast to add inline text to this PDF. What system do you have?

I encounter the issue on 2 machines I have running Pop!_OS 22.04 LTS running the AppImage (from Github) and the Flatpak.
I'll be back home in a few days and I'll try it on a Linux Mint machine I have and let you know how it works there as well.

**Comment by JakubMelka** [comment]
@TriggerDingus, could you please try a new AppImage version 1.4.0.0?

**Comment by TriggerDingus** [comment]
Greetings. I downloaded the new AppImage and gave it permissions to run as a program, but it isn't working. On the GUI, if I double-click it to execute, it does nothing. When I try running it from the CLI, it throws the error "command not found".

**Comment by JakubMelka** [comment]
@TriggerDingus, could you please try to install libxcb-cursor0?

**Comment by TriggerDingus** [comment]
Yes, the latency issues appears to be resolved in the AppImage with the additional experimental library directly installed. I'll watch for the Flatpak version 1.4 to come out since that's my preference.  

As an FYI, which is probably an additional issue, I first tried using the attached PDF to test the latency issue it but neither the viewer or editor would open this file (I later tested with a different PDF that did open).  To clarify, it did open the proper number of pages (3), but all three are blank.  This PDF file is viewable by any of my other PDF viewers, but there's apparently something in it that PDF4QT doesn't like.  (see attached)
[Lead Sheet - Andy Wright MOG version.pdf](https://github.com/user-attachments/files/16113788/Lead.Sheet.-.Andy.Wright.MOG.version.pdf)

**Comment by JakubMelka** [comment]
@TriggerDingus, I have tried to fix issue with the attached PDF. Please have a look on it. I think we can close this issue, as workaround exists?

**Comment by TriggerDingus** [comment]
Agreed. Thx
