### ISSUE TITLE
Expected 48 char long string in entry "O". Provided lenght is 127

### ISSUE THREAD

**Issue by FFernandez1** [JakubMelka/PDF4QT#167]
Hi! Thank you for this amazing tool.

When trying to open certain PDFs, I'm getting the following error message:

![error - copy](https://github.com/JakubMelka/PDF4QT/assets/92254869/284120dc-8127-4a3e-96de-a4bea2a20470)

These PDFs can be opened using the browser or Foxit, so apparently, there aren't any issues with them.

Please let me know if you need more details.

Thank you

**Comment by JakubMelka** [comment]
Hello @FFernandez1 , could you please provide sample bad PDF?

**Comment by FFernandez1** [comment]
Hi @JakubMelka ! Unfortunately, the files cannot be publicly shared.

How would you like me to provide them?

**Comment by FFernandez1** [comment]
Hi @JakubMelka , actually I´ve seen that this issue has already been reported here:

https://github.com/JakubMelka/PDF4QT/issues/163

The issue is reproducible with the following document:
[MCP23017-Data-Sheet-DS20001952.pdf](https://github.com/JakubMelka/PDF4QT/files/14396996/MCP23017-Data-Sheet-DS20001952.pdf)

Original link: https://ww1.microchip.com/downloads/aemDocuments/documents/APID/ProductDocuments/DataSheets/MCP23017-Data-Sheet-DS20001952.pdf

Virustotal scan:
https://www.virustotal.com/gui/url/dfb5828738a130a68fbce652d38a6301e05039add4c5fd05ef2c11aef186527f?nocache=1

**Comment by JakubMelka** [comment]
@FFernandez1: Document can be opened now.

**Comment by cweiske** [comment]
I have the same problem with the 1.3.7 appimage version. Could you please release a new version?
The [last CI run](https://github.com/JakubMelka/PDF4QT/actions/runs/8348750839) artifacts have expired already, so I can't download from there.

**Comment by JakubMelka** [comment]
@cweiske: I have started the CI run again to prepare Linux Installations. The problem is, I do not have a certificate to sign the installation (I must buy it, I plan it in june).

**Comment by cweiske** [comment]
This is very unfortunate :(
I guess you already checked if you can create a certificate yourself instead of relying on a bought certificate.
As far as I know its enough if all releases are signed by the same certificate, and that EV certificates are not required.

**Comment by cweiske** [comment]
Thanks, I could download + use PDF4QT now.
