### ISSUE TITLE
When opening a PDF file or merging some PDF files, stamp will disappear.

### ISSUE THREAD

**Issue by hongyi-zhao** [JakubMelka/PDF4QT#168]
See the following file:

![image](https://github.com/JakubMelka/PDF4QT/assets/11155854/3daf9e73-e685-4eb6-8a65-d2987d7b5737)

When I open it with https://github.com/JakubMelka/PDF4QT/releases/download/v1.3.7/PDF4QT_Viewer_Profi-0629a71-x86_64.AppImage, the result is as follows:

![image](https://github.com/JakubMelka/PDF4QT/assets/11155854/0cd7ea05-9243-4a74-8eac-07bd2c3668b1)

Regards,
Zhao

**Comment by JakubMelka** [comment]
Hello @hongyi-zhao , could you please provide PDF file, not a screenshot? Do you have checked this feature:
![image](https://github.com/JakubMelka/PDF4QT/assets/11367048/931ce90d-b0f9-4393-920c-984d6a49a9ab)
?

**Comment by hongyi-zhao** [comment]
I attached the pdf file here.

BTW, the above-mentioned feature is enabled by default.

[文献检索报告1.pdf](https://github.com/JakubMelka/PDF4QT/files/14427245/1.pdf)

**Comment by hongyi-zhao** [comment]
This issue may be related to the following characteristics of the stamp:
![image](https://github.com/JakubMelka/PDF4QT/assets/11155854/49425b2d-0e77-4387-af23-d32b3967891c)

If I merge the following two documents in qoppa pdf studio 2023, the stamp of the second file in the resulting pdf is also lost, but merging with pdfsam has no such problem.
[文献检索报告1.pdf](https://github.com/JakubMelka/PDF4QT/files/14427328/1.pdf)
[文献检索报告2.pdf](https://github.com/JakubMelka/PDF4QT/files/14427329/2.pdf)

**Comment by JakubMelka** [comment]
Hello, now, it is displayed always. You can try it at this link: https://github.com/JakubMelka/PDF4QT/actions/runs/8101084553

**Comment by hongyi-zhao** [comment]
I tried and the problem has been fixed now.

BTW, how can I combine/merge several PDF files with this tool?

**Comment by JakubMelka** [comment]
Hello, application PDF4QT DocPage Organizer is for merging/splitting PDF files. I will make it available it in AppImage also.
