### ISSUE TITLE
_Zls6QDebugRK11QDockWidget symbol not found

### ISSUE THREAD

**Issue by ethanc8** [JakubMelka/PDF4QT#170]
Hello, I am using KDE Neon User, based on Ubuntu 22.04 with KDE Plasma 6 and Qt 6.6.2. I have installed the Flatpak from [Flathub](https://flathub.org/apps/io.github.JakubMelka.Pdf4qt). When trying to run it from the desktop environment, it does not launch, and if I run it from the command line:

```
$ flatpak run --branch=stable --arch=x86_64 --command=Pdf4QtDocPageOrganizer io.github.JakubMelka.Pdf4qt
Pdf4QtDocPageOrganizer: symbol lookup error: /app/bin/../lib/libPdf4QtLibWidgets.so.1.3.7: undefined symbol: _Zls6QDebugRK11QDockWidget, version Qt_6
```

This issue did not appear before when I was still using Plasma 5 and Qt 5.15 with KDE patches. I have not yet tested the AppImage, and will report back here when I have.

**Comment by caedmon-kitty** [comment]
Same here.  Installed and tried to run the flatpak on Fedora 39.

**Comment by JakubMelka** [comment]
Hello @ethanc8, that is strange... Did AppImage help?

**Comment by ethanc8** [comment]
I haven't had time to look at the AppImage.

**Comment by caedmon-kitty** [comment]
For me the appimage works flawlessly.

**Comment by JakubMelka** [comment]
@ethanc8, I think something is with your system. 

Please to try these commands:

flatpak list --runtime
flatpak install flathub org.kde.Platform//6.6
flatpak update

Then please try:
flatpak run --command=Pdf4QtDocPageOrganizer io.github.JakubMelka.Pdf4qt --verbose

**Comment by JakubMelka** [comment]
I have released a new version. Workaround aroud bug exists (use AppImage), so you can use just AppImage to solve this.
