### ISSUE TITLE
errors loading file Echoplex.pdf

### ISSUE THREAD

**Issue by sean-e** [JakubMelka/PDF4QT#173]
The attached file is not readable by PDF4QT Viewer Profi.  
It seems to load properly in SumatraPDF.
[Echoplex.pdf](https://github.com/JakubMelka/PDF4QT/files/14643466/Echoplex.pdf)

**Comment by JakubMelka** [comment]
I've fixed it so that the text is displayed, but because the fonts are not embedded, they've been replaced with a default font, which doesn't look very good.
