### ISSUE TITLE
Support for Linux seems to be very limited

### ISSUE THREAD

**Issue by Kerneels90** [JakubMelka/PDF4QT#174]
In the introduction and videos about the DFS4QT app, you get the impression PDF4QT is fully functional on Linux. However, this seems not to be the case. When trying to install the deb file, I got a "have unmet dependencies" error.  After some researching, I only got the PDF4QT_Viewer_Profi-0629a71-x86_64.AppImage  component running (AppImage is something new to me. Some help in this regard would have helped a lot.) Whether the Linux deb version supports all the PDF4QT programs, I still have to see. I needed especially the DocPage Organizer part. The deb version seems at best to be an earlier version. However, the program will a valuable asset once the teething errors are sorted out.

**Comment by JakubMelka** [comment]
Hello @Kerneels90, please use AppImage from daily build: https://github.com/JakubMelka/PDF4QT/actions/runs/8348750839 , where you can select which application to run.

**Comment by JakubMelka** [comment]
@Kerneels90:
I have released version 1.4.0.0. Download **PDF4QT-1.4.0.0-x86_64.AppImage**, then just run it, and you can select from 4 applications.
![image](https://github.com/JakubMelka/PDF4QT/assets/11367048/21c756ee-8e36-40e8-83e3-003baf4d777e)
Please reopen this issue, if you think it is not solved.
