### ISSUE TITLE
PDF4QT editor and options windows higher than desktop

### ISSUE THREAD

**Issue by cweiske** [JakubMelka/PDF4QT#180]
The PDF4QT editor and option windows are higher than the available desktop height. This makes it hard to reach the OK/Cancel buttons in the options window, and I can't maximize the main window because it's too high.

This is on Debian unstable with PDF4QT AppImage from from https://github.com/JakubMelka/PDF4QT/actions/runs/8883454760 (commit https://github.com/JakubMelka/PDF4QT/commit/c9b262fc36d2b2b2f9996099cccf3940987816c2)
The display has a resolution of 1920x1080 with 166 dpi (not hidpi but more a mdpi). To scale the fonts correctly I use the `QT_FONT_DPI=125` environment variable.

It would be nice if the options dialog would get a vertical scroll bar when needed, and the main window would get a vertical scrollbar for the buttons on the left side.

The problem in the options window seems to be the "Colors | CMS" options that seem to prevent making the options window smaller.

# Screenshots
Main window:
![2024-05-01 pdf4qt desktop](https://github.com/JakubMelka/PDF4QT/assets/59036/a17848ba-d5c6-4e76-8f09-2de7d7144445)

Options window:
![2024-05-01 pdf4qt desktop options](https://github.com/JakubMelka/PDF4QT/assets/59036/3da0ab11-231b-4efe-81b6-9fb12ab0df89)

Options after moving the window up by pressing `Alt` + moving it with the mouse:
![2024-05-01 pdf4qt desktop options 2](https://github.com/JakubMelka/PDF4QT/assets/59036/e9c05b6d-9464-462e-9ab3-da325fd06394)

**Comment by JakubMelka** [comment]
@cweiske, the issue should be resolved. I have added text browsers to the help text and introduced QScrollArea to the buttons.

**Comment by cweiske** [comment]
Works fine in 1.4.0. Thank you!
