### ISSUE TITLE
where is the dark mode?

### ISSUE THREAD

**Issue by Tearony** [JakubMelka/PDF4QT#181]
maybe I am just stupid, but I can't seem to find the dark mode. It does seem to exist, and icons are available since the last version. I have searched every option I could find. I used the msi installer and the portable version (even a former version) but I couldn't find the dark mode anywhere.

Is there something I should know here?

**Comment by JakubMelka** [comment]
Hello @Tearony,
dark mode should be automatically detected from system palette:
![image](https://github.com/JakubMelka/PDF4QT/assets/11367048/30fcbc24-ce75-428d-9e3e-b0207f6fe4fd)
So, if you use dark theme on your PC, it should automatically turn on.

**Comment by Tearony** [comment]
what could be the problem then, because I definetly use dark Mode System wide

**Comment by JakubMelka** [comment]
@Tearony , I have changed detection method for the dark mode. It should be OK now.
