### ISSUE TITLE
PDF4QT Document Diff command line cmd line arguments ignored

### ISSUE THREAD

**Issue by paucoma** [JakubMelka/PDF4QT#182]
### GUI Tool:  **PDF4QT Document Diff**

**_Description of the problem:_**
PDF4QTDocDiff **does not open command line provided arguments** as described in help.

![image](https://github.com/JakubMelka/PDF4QT/assets/4084071/d34a5ccd-d155-4729-b37b-a791816d9ba3)

_**To Reproduce:**_ 
Open a command line prompt : `Pdf4QtDocDiff c:\usr\tmp\a.pdf c:\usr\tmp\b.pdf`

_**Expected behavior**_
To Open the GUI of PDF4QTDocDiff with first positional Argument as left Document and second Positional Argument as right Document loaded.

_**My Investigation**_
I have scanned through the source code and **it appears as if this is not implemented in the GUI code**.
 
PDFtool does implement the expected behaviour of taking into consideration the positional arguments
`PdfTool.exe diff c:\usr\tmp\a.pdf c:\usr\tmp\b.pdf `
the source code take the positional arguments into consideration:
` QStringList positionalArguments = parser->positionalArguments();` [code permalink](https://github.com/JakubMelka/PDF4QT/blob/c9b262fc36d2b2b2f9996099cccf3940987816c2/PdfTool/pdftoolabstractapplication.cpp#L349)
`options.diffFiles = positionalArguments;` [code permalink](https://github.com/JakubMelka/PDF4QT/blob/c9b262fc36d2b2b2f9996099cccf3940987816c2/PdfTool/pdftoolabstractapplication.cpp#L894
)
`pdf::PDFDocument leftDocument = reader.readFromFile(options.diffFiles.front());` [code permalink](https://github.com/JakubMelka/PDF4QT/blob/c9b262fc36d2b2b2f9996099cccf3940987816c2/PdfTool/pdftooldiff.cpp#L59)

_**How I would use it:**_
I have created a simple **Batch script** in the **sendTo** section of windows to open files for comparison directly from with the windows file explorer content menu. Much quicker than navigating from within the GUI ounce is is open to the file location that you have open within the file explorer.

 **pdf-diff.bat**
>            C:\opt\PDF4QT\Pdf4QtDocDiff.exe "%~f1" "%~f2"

**_Environment:_**
OS: Windows 11 Pro version 23H2
PDF4QT Document Diff 1.3.7

**Comment by JakubMelka** [comment]
Fixed.
