### ISSUE TITLE
Form field font size too large

### ISSUE THREAD

**Issue by cweiske** [JakubMelka/PDF4QT#184]
When filling a form with PDF4QT Editor 1.3.7 (AppImage), the font size in form fields is too large.
- When tabbing out of the field, the lower part of the written words are not visible anymore
- When typing in the field, the cursor is much further right than the letters are

![2024-06-03 pdf4qt form](https://github.com/JakubMelka/PDF4QT/assets/59036/54f74b92-55ed-48f1-a285-6faa4d4677f7)

Example PDF form:
https://regionalbusleipzig.de/media/pages/tickets/schueler-azubis/7f405ccd76-1712565425/formular_bestellung_bildungsticket_rl.pdf
Page 2, section 1.1

**Comment by JakubMelka** [comment]
@cweiske, I hope it is fixed.

**Comment by cweiske** [comment]
The cursor issue is fixed, the font size issue not.
Text in form fields is vertically aligned at the bottom now, so that the upper parts of the words (dots on `iäöü`) are not visible.

When text is wider than the field (birthdate "Geburtsdatum") it should be scaled down as well.

![2024-07-14 pdf4qt font 1 4 0](https://github.com/user-attachments/assets/64de302a-7675-4d27-ae30-b294d247e209)

**Comment by JakubMelka** [comment]
@cweiske, to apply fix, please try to edit form fields again (for example delete text and insert it again). Did it help?

**Comment by cweiske** [comment]
I opened a fresh pdf without any filled form values and started to enter them fresh. Deleting the entered text and inserting them again does not help.
