### ISSUE TITLE
There are no plugins in Pdf4QtEditor

### ISSUE THREAD

**Issue by Jajasek** [JakubMelka/PDF4QT#195]
First of all, thank you for your excellent work, it looks extremely powerful. Unfortunately, I have not been able to enable the Editor plugin.
I have latest git (commit [2a93ca5](https://github.com/JakubMelka/PDF4QT/commit/2a93ca5a1f40ee8178f07ac1590889c3d2623d6c) installed on Arch via AUR. When I run `Pdf4QtEditor` and go to `Tools > Options > Plugins`, there is an empty table, no plugins are available. On stdout there is a message `Error loading text-to-speech plug-in "speechd"`, which is expected as I have no text-to-speech library installed, but no messages about other plugins. Is it possible that when the speechd plugin fails to load, the whole plugin-loading process terminates and no other plugins are loaded?

**Comment by SnowballV** [comment]
@Jajasek,
If you used or tested a previous version earlier on, you may need to reset to factory settings to get all options shown.
That was my experience with PDF4QT-1.4.0.0-x86_64.AppImage on Kubuntu 22.04, after testing PDF4QT 1.3.7 and daily builds earlier on.

**Comment by Jajasek** [comment]
@SnowballV thanks for the tip, unfortunately it still doesn't show any plugins.

**Comment by raffaem** [comment]
If you are using my pdf4qt-git package, as I think you are if you are installing from the AUR, I am experiencing problems uploading the package to the AUR.

Please try the PKGBUILD here: https://github.com/raffaem/pdf4qt-git-pkgbuild

**Comment by raffaem** [comment]
@Jajasek if it works now please close the issue

**Comment by Jajasek** [comment]
Thank you, it works now.
