### ISSUE TITLE
Cannot install it

### ISSUE THREAD

**Issue by Tobilike** [JakubMelka/PDF4QT#197]
Hi I am using Arch Linux and the package in AUR does not work. I get an error message. Installation failed.
I tried the version in Flathub next, but it won't run. (Pdf4QtViewerProfi: symbol lookup error: /app/bin/../lib/libPdf4QtLibWidgets.so.1.3.7: undefined symbol: _Zls6QDebugRK11QDockWidget, version Qt_6)
This version also seems to be outdated. 

Greetings

**Comment by raffaem** [comment]
Please install `pdf4qt-git` from the AUR

**Comment by Tobilike** [comment]
This version works. 
Thank you.

**Comment by raffaem** [comment]
@Tobilike please close the issue if it works for you

**Comment by Tobilike** [comment]
The Flatpak version is still outdated and does not work. Problem has not been fixed yet.

**Comment by PenelopeFudd** [comment]
Here's what happens on a Fedora 40 system:
```
$ sudo flatpak install pdf4qt
 
Looking for matches…
Found ref ‘app/io.github.JakubMelka.Pdf4qt/x86_64/stable’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: y
Required runtime for io.github.JakubMelka.Pdf4qt/x86_64/stable (runtime/org.kde.Sdk/x86_64/6.6) found in remote flathub
Do you want to install it? [Y/n]: y

io.github.JakubMelka.Pdf4qt permissions:
    ipc     fallback-x11     wayland     x11     dri     file access [1]     dbus access [2]

    [1] xdg-config/kdeglobals:ro
    [2] com.canonical.AppMenu.Registrar


        ID                                               Branch                 Op            Remote             Download
 1. [✓] org.freedesktop.Platform.GL.default              23.08                  u             flathub              7.5 MB / 163.8 MB
 2. [✓] org.freedesktop.Platform.GL.default              23.08-extra            u             flathub              5.9 MB / 163.8 MB
 3. [✓] org.freedesktop.Platform.VAAPI.Intel             23.08                  u             flathub            789.6 kB / 13.5 MB
 4. [✓] org.kde.Sdk.Locale                               6.6                    i             flathub             18.1 kB / 397.8 MB
 5. [✓] org.kde.Sdk                                      6.6                    i             flathub            593.4 MB / 844.7 MB
 6. [✓] io.github.JakubMelka.Pdf4qt                      stable                 i             flathub              9.0 MB / 9.4 MB

Changes complete.
 
$ flatpak list

Name                                   Application ID                                    Version                          Branch             Origin         Installation
PDF4QT                                 io.github.JakubMelka.Pdf4qt                       1.3.7                            stable             flathub        system
Fedora Platform                        org.fedoraproject.Platform                        40                               f40                fedora         system
Freedesktop Platform                   org.freedesktop.Platform                          freedesktop-sdk-22.08.26         22.08              flathub        system
Freedesktop Platform                   org.freedesktop.Platform                                                           23.08              flathub        system
i386                                   org.freedesktop.Platform.Compat.i386                                               23.08              flathub        system
Mesa                                   org.freedesktop.Platform.GL.default               24.0.9                           22.08              flathub        system
Mesa (Extra)                           org.freedesktop.Platform.GL.default               24.0.9                           22.08-extra        flathub        system
Mesa                                   org.freedesktop.Platform.GL.default               24.2.3                           23.08              flathub        system
Mesa (Extra)                           org.freedesktop.Platform.GL.default               24.2.3                           23.08-extra        flathub        system
Mesa                                   org.freedesktop.Platform.GL32.default             24.2.1                           23.08              flathub        system
Intel                                  org.freedesktop.Platform.VAAPI.Intel                                               22.08              flathub        system
Intel                                  org.freedesktop.Platform.VAAPI.Intel                                               23.08              flathub        system
i386                                   org.freedesktop.Platform.VAAPI.Intel.i386                                          23.08              flathub        system
openh264                               org.freedesktop.Platform.openh264                 2.1.0                            2.2.0              flathub        system
KDE Application Platform               org.kde.Platform                                                                   5.15-23.08         flathub        system
KDE Application Platform               org.kde.Platform                                                                   6.6                flathub        system
KDE Software Development Kit           org.kde.Sdk                                                                        6.6                flathub        system

$ flatpak run io.github.JakubMelka.Pdf4qt

Pdf4QtViewerProfi: symbol lookup error: /app/bin/../lib/libPdf4QtLibWidgets.so.1.3.7: undefined symbol: _Zls6QDebugRK11QDockWidget, version Qt_6
```

**Comment by boustanihani** [comment]
> Here's what happens on a Fedora 40 system:
> 
> ```
> $ sudo flatpak install pdf4qt
>  
> Looking for matches…
> Found ref ‘app/io.github.JakubMelka.Pdf4qt/x86_64/stable’ in remote ‘flathub’ (system).
> Use this ref? [Y/n]: y
> Required runtime for io.github.JakubMelka.Pdf4qt/x86_64/stable (runtime/org.kde.Sdk/x86_64/6.6) found in remote flathub
> Do you want to install it? [Y/n]: y
> 
> io.github.JakubMelka.Pdf4qt permissions:
>     ipc     fallback-x11     wayland     x11     dri     file access [1]     dbus access [2]
> 
>     [1] xdg-config/kdeglobals:ro
>     [2] com.canonical.AppMenu.Registrar
> 
> 
>         ID                                               Branch                 Op            Remote             Download
>  1. [✓] org.freedesktop.Platform.GL.default              23.08                  u             flathub              7.5 MB / 163.8 MB
>  2. [✓] org.freedesktop.Platform.GL.default              23.08-extra            u             flathub              5.9 MB / 163.8 MB
>  3. [✓] org.freedesktop.Platform.VAAPI.Intel             23.08                  u             flathub            789.6 kB / 13.5 MB
>  4. [✓] org.kde.Sdk.Locale                               6.6                    i             flathub             18.1 kB / 397.8 MB
>  5. [✓] org.kde.Sdk                                      6.6                    i             flathub            593.4 MB / 844.7 MB
>  6. [✓] io.github.JakubMelka.Pdf4qt                      stable                 i             flathub              9.0 MB / 9.4 MB
> 
> Changes complete.
>  
> $ flatpak list
> 
> Name                                   Application ID                                    Version                          Branch             Origin         Installation
> PDF4QT                                 io.github.JakubMelka.Pdf4qt                       1.3.7                            stable             flathub        system
> Fedora Platform                        org.fedoraproject.Platform                        40                               f40                fedora         system
> Freedesktop Platform                   org.freedesktop.Platform                          freedesktop-sdk-22.08.26         22.08              flathub        system
> Freedesktop Platform                   org.freedesktop.Platform                                                           23.08              flathub        system
> i386                                   org.freedesktop.Platform.Compat.i386                                               23.08              flathub        system
> Mesa                                   org.freedesktop.Platform.GL.default               24.0.9                           22.08              flathub        system
> Mesa (Extra)                           org.freedesktop.Platform.GL.default               24.0.9                           22.08-extra        flathub        system
> Mesa                                   org.freedesktop.Platform.GL.default               24.2.3                           23.08              flathub        system
> Mesa (Extra)                           org.freedesktop.Platform.GL.default               24.2.3                           23.08-extra        flathub        system
> Mesa                                   org.freedesktop.Platform.GL32.default             24.2.1                           23.08              flathub        system
> Intel                                  org.freedesktop.Platform.VAAPI.Intel                                               22.08              flathub        system
> Intel                                  org.freedesktop.Platform.VAAPI.Intel                                               23.08              flathub        system
> i386                                   org.freedesktop.Platform.VAAPI.Intel.i386                                          23.08              flathub        system
> openh264                               org.freedesktop.Platform.openh264                 2.1.0                            2.2.0              flathub        system
> KDE Application Platform               org.kde.Platform                                                                   5.15-23.08         flathub        system
> KDE Application Platform               org.kde.Platform                                                                   6.6                flathub        system
> KDE Software Development Kit           org.kde.Sdk                                                                        6.6                flathub        system
> 
> $ flatpak run io.github.JakubMelka.Pdf4qt
> 
> Pdf4QtViewerProfi: symbol lookup error: /app/bin/../lib/libPdf4QtLibWidgets.so.1.3.7: undefined symbol: _Zls6QDebugRK11QDockWidget, version Qt_6
> ```

Having same issue witrh the flatpak version.

**Comment by JakubMelka** [comment]
Hello @Tobilike, @PenelopeFudd, @boustanihani, I have updated the flatpak version. Please try the newest one.

**Comment by JakubMelka** [comment]
It should be fixed by now. Please reopen the issue, if it reappears.
