### ISSUE TITLE
UI scaling

### ISSUE THREAD

**Issue by Baeldaeg** [JakubMelka/PDF4QT#201]
Is there a way to scale the UI? It's so small I can barely see it.
Using the linux appimage on a laptop with a high DPI screen.
![12 31 37](https://github.com/user-attachments/assets/472954ae-5138-4570-8112-6a3d92b40528)

**Comment by JakubMelka** [comment]
Hello @Baeldaeg, could you please try to set the value of QT_SCALE_FACTOR to 2 (it is environmental variable). See https://doc.qt.io/qt-6/highdpi.html.

**Comment by Baeldaeg** [comment]
That's worked, thank you.
