### ISSUE TITLE
Editor cannot create white, whitesmoke or transparent annotations

### ISSUE THREAD

**Issue by AlisterH** [JakubMelka/PDF4QT#205]
If I try to set the colour or interior colour of an annotation to white, whitesmoke, or transparent, it instead selects black.
I note that I can create white annotations in another pdf viewer and pdf4qt editor can cope with them - I was able to use it to copy a white rectangle onto all the other pages in a document.

**Comment by JakubMelka** [comment]
Hello @AlisterH, it was just a minor issue when the color value of the combo box was loaded, but it has been fixed.
