### ISSUE TITLE
Name of the executable / command

### ISSUE THREAD

**Issue by mattzjack** [JakubMelka/PDF4QT#206]
Perhaps I was being negligent -- is the name of the command / executable mentioned somewhere? I spent a decent 5 minutes trying to launch it, until I realise it's `Pdf4QtXXX` with a capital `P`. It would be nice to mention this somewhere easy to find, like in README.md :slightly_smiling_face:

**Comment by JakubMelka** [comment]
I have adjusted the README.txt file, and the program names are now mentioned.
