### ISSUE TITLE
Zoom to Cursor (Zoom Anchoring)

### ISSUE THREAD

**Issue by TranquilMind97** [JakubMelka/PDF4QT#207]
Greetings,
Appreciate all the hard work in creating an open-source pdf editor. Nice Work.👍

Is it possible to add "zoom to location of the cursor" feature? 
This is handy since most users intuitively place the cursor at the location they are interested in zooming to. Seems most pdf reader have this by default too.

"Zoom to Cursor" feature in Foxit pdf Reader:
<img src="https://github.com/user-attachments/assets/23a6e2be-32b2-44e9-80c8-fd132f0eedd1" width="500" height="300">

"Zooming" in PDF4QT: (Seems to zoom to top left corner regardless of cursor position)
<img src="https://github.com/user-attachments/assets/d7800199-03b9-4bd4-9a08-1df2f688a2b1" width="500" height="300">

Thank you & have a great day.

**Comment by JakubMelka** [comment]
Hello @TranquilMind97, I have fixed it.
