### ISSUE TITLE
Flatpak Won't Open in Fedora 41

### ISSUE THREAD

**Issue by rexmtorres** [JakubMelka/PDF4QT#214]
Just check the reviews for the Flatpak version.  Everyone's complaining that it won't launch.  I already tried giving it all the permissions and file system access.

**Comment by dreua** [comment]
I think this is a duplicate of #212

**Comment by JakubMelka** [comment]
Hello @rexmtorres, please try the updated flatpak package.

**Comment by rexmtorres** [comment]
> Hello @rexmtorres, please try the updated flatpak package.

Hello.  Where can I find it?  I can neither find it in Flathub, nor here in under releases (latest version is from July).

**Comment by dreua** [comment]
On the flathub.org website I see a new build: "5 months ago (Built about 16 hours ago)"

**Comment by JakubMelka** [comment]
@dreua , @rexmtorres, that is because the last release was in the July, I do not incremented the version.

**Comment by dreua** [comment]
Yes, that is what I wanted to say. Not sure which app this is in @rexmtorres' screenshot but it either has outdated data (cached?) or is unable to show the last build and only shows the data of new releases.

**Comment by JakubMelka** [comment]
I think the most important thing is if the application works or not and not the correct version number. Have you tried it?
