### ISSUE TITLE
mingw compiler error on windows

### ISSUE THREAD

**Issue by davidche1116** [JakubMelka/PDF4QT#217]
github action：
[WindowsMinGWBuild.zip](https://github.com/user-attachments/files/17657860/WindowsMinGWBuild.zip)

Can you help me see what needs to be changed

https://github.com/microsoft/vcpkg/issues/40683

[cmake] Installing 23/23 tbb:x64-mingw-static@2022.0.0...
[cmake] Building tbb:x64-mingw-static@2022.0.0...
[cmake] D:\Code\github\vcpkg\triplets\community\x64-mingw-static.cmake: info: loaded community triplet from here. Community triplets are not built in the curated registry and are thus less likely to succeed.
[cmake] -- Using cached oneapi-src-oneTBB-v2022.0.0.tar.gz.
[cmake] -- Cleaning sources at D:/Code/github/vcpkg/buildtrees/tbb/src/v2022.0.0-3c0387beea.clean. Use --editable to skip cleaning for the packages you specify.
[cmake] -- Extracting source D:/Code/github/vcpkg/downloads/oneapi-src-oneTBB-v2022.0.0.tar.gz
[cmake] -- Using source at D:/Code/github/vcpkg/buildtrees/tbb/src/v2022.0.0-3c0387beea.clean
[cmake] -- Configuring x64-mingw-static
[cmake] CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
[cmake]     Command failed: D:/Code/github/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
[cmake]     Working Directory: D:/Code/github/vcpkg/buildtrees/tbb/x64-mingw-static-rel/vcpkg-parallel-configure
[cmake]     Error code: 1
[cmake]     See logs for more information:
[cmake]       D:\Code\github\vcpkg\buildtrees\tbb\config-x64-mingw-static-dbg-CMakeCache.txt.log
[cmake]       D:\Code\github\vcpkg\buildtrees\tbb\config-x64-mingw-static-rel-CMakeCache.txt.log
[cmake]       D:\Code\github\vcpkg\buildtrees\tbb\config-x64-mingw-static-dbg-CMakeConfigureLog.yaml.log
[cmake]       D:\Code\github\vcpkg\buildtrees\tbb\config-x64-mingw-static-rel-CMakeConfigureLog.yaml.log
[cmake]       D:\Code\github\vcpkg\buildtrees\tbb\config-x64-mingw-static-out.log
[cmake] 
[cmake] Call Stack (most recent call first):
[cmake]   C:/Users/Administrator/Desktop/qq/PDF4QT/build/Desktop_Qt_6_8_0_MinGW_64_bit-Release/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:269 (vcpkg_execute_required_process)
[cmake]   ports/tbb/portfile.cmake:17 (vcpkg_cmake_configure)
[cmake]   scripts/ports.cmake:192 (include)
[cmake] 
[cmake] 
[cmake] error: building tbb:x64-mingw-static failed with: BUILD_FAILED
[cmake] See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
[cmake] Elapsed time to handle tbb:x64-mingw-static: 3.2 s
[cmake] Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
[cmake] Then check for known issues at:
[cmake]   https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+tbb
[cmake] You can submit a new issue at:
[cmake]   https://github.com/microsoft/vcpkg/issues/new?title=[tbb]+Build+error+on+x64-mingw-static&body=Copy+issue+body+from+C%3A%2FUsers%2FAdministrator%2FDesktop%2Fqq%2FPDF4QT%2Fbuild%2FDesktop_Qt_6_8_0_MinGW_64_bit-Release%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md
[cmake] 
[cmake] -- Running vcpkg install - failed
[cmake] CMake Error at D:/Code/github/vcpkg/scripts/buildsystems/vcpkg.cmake:904 (message):
[cmake]   vcpkg install failed.  See logs for more information:
[cmake]   C:\Users\Administrator\Desktop\qq\PDF4QT\build\Desktop_Qt_6_8_0_MinGW_64_bit-Release\vcpkg-manifest-install.log
[cmake] Call Stack (most recent call first):
[cmake]   build/Desktop_Qt_6_8_0_MinGW_64_bit-Release/vcpkg-dependencies/toolchain.cmake:6 (include)
[cmake]   D:/Qt/Qt6.8/Tools/CMake_64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:146 (include)
[cmake]   CMakeLists.txt:23 (project)
[cmake] 
[cmake] 
[cmake] CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
[cmake] -- Configuring incomplete, errors occurred!
[cmake] 
[cmake] The command "D:\Qt\Qt6.8\Tools\CMake_64\bin\cmake.exe -S C:/Users/Administrator/Desktop/qq/PDF4QT -B C:/Users/Administrator/Desktop/qq/PDF4QT/build/Desktop_Qt_6_8_0_MinGW_64_bit-Release" terminated with exit code 1.
[cmake] 
[cmake] Elapsed time: 08:17.

**Comment by davidche1116** [comment]
same with #44

**Comment by JakubMelka** [comment]
Hello @davidche1116 , could you please update VCPKG to the lastest version?

**Comment by davidche1116** [comment]
@JakubMelka ，I use the github action script as follows:
      - name: 'VCPKG: Set up VCPKG'
        run: |
          git clone --depth=1 https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat -disableMetrics
          .\vcpkg integrate install
          set VCPKG_ROOT=${env:GITHUB_WORKSPACE}\vcpkg\
          set "VCPKG_BINARY_SOURCES=clear;files,${env:GITHUB_WORKSPACE}\vcpkg\archives,readwrite"

**Comment by JakubMelka** [comment]
Hello @davidche1116, unfortunately, tbb is not supported for the MinGW compiler. See, for example, issue https://github.com/microsoft/vcpkg/issues/42046 . As this problem is outside of PDF4QT project, I will close this issue.
