### ISSUE TITLE
[feature] reverse pages order

### ISSUE THREAD

**Issue by hubaishan** [JakubMelka/PDF4QT#228]
I suggest feature to reverse pages order from last to first. The need for this feature for Right to Left books (like Arabic, Persian…) scanned as Left to Right book and published as PDF, many of them on the internet. This feature will be useful to correct order of pages.

**Comment by JakubMelka** [comment]
Hello @hubaishan, I have implemented this feature in PageMaster. Please try it, when the installation will be prepared. I will close it, but reopen it, if you think something is missing.
