### ISSUE TITLE
Can this program be submitted to flathub for flatpak?

### ISSUE THREAD

**Issue by jointri** [JakubMelka/PDF4QT#23]
Having your program on flatpak via flathub will give it enormous exposure and it would be great to be able to seamlessly set it up using a program that me and others are already familiar with.

You can find info on submitting application here:
https://github.com/flathub/flathub/wiki/App-Submission

If you don't wish to do the submission yourself, may I have your permission to pack this up for flathub and flatpak?

**Comment by JakubMelka** [comment]
Hello, I think that is good idea. I will look onto it tomorrow. That is my problem - I am programmer, not marketing specialist, so I do not know how to promote my software. And yes - I want to include also Linux installation, and I do not know hot to create packages for Linux, so flatpack is a good idea. Thank you for this advice.

**Comment by jointri** [comment]
That's awesome to hear man. If you're not already aware of it, conan docs that you use for linux compilation have a section all about flatpak.
https://docs.conan.io/en/latest/integrations/deployment/flatpak.html
So it should be a piece of cake to pack it up for flatpak once you get the hang of the config files.

If you also wish to have it on the snap store ran by canonical who make ubuntu or maybe even deploy as an appimage, you have that as an option as well. I say the more the merrier.
https://docs.conan.io/en/latest/integrations/deployment/snap.html
https://docs.conan.io/en/latest/integrations/deployment/appimage.html
https://docs.conan.io/en/latest/integrations/deployment.html

**Comment by JakubMelka** [comment]
I use a QBS system to built on linux. I think flatpack cannot use QBS? qmake must be used? I do not know, where to start. I have a few questions:

- Flatpack downloads my dependencies (if I use the way used above) ?
- Flatpack builds my source code using qmake?

**Comment by jointri** [comment]
https://docs.flatpak.org/en/latest/manifests.html
qmake is one option to build a flatpak app. You can also use meson, cmake, or even traditional autotools. There is a possibility you might have to switch build system because qbs is deprecated anyways by the qt company. I can offer assistance with switch to cmake. You don't have to use qmake, it's just one option. Flatpak will handle all dependencies for you and all you have to do is tell flatpak the app permissions and what dependencies are required. The buildbot will construct it for you and do all the complicated work itself. You should fork https://github.com/flathub/flathub and check out other pull requests here: https://github.com/flathub/flathub/pulls to get the idea of how to submit your app to flathub. You can have it built and tested entirely through github.

**Comment by jointri** [comment]
If this one is to be any indication, I think you CAN use qbs with flatpak. https://github.com/flathub/flathub/pull/654

**Comment by JakubMelka** [comment]
OK, tommorrow, I will try to do some basic initialisation.

**Comment by jointri** [comment]
May I have your permission to write up a flatpak for you and make a pull request?

**Comment by jointri** [comment]
@JakubMelka What I am offering to do is write up the xml/json files on github that flathub-builder will use and send a PR to flathub github repo. It's actually pretty simple to build for flatpak, don't need to have linux installed at all.

**Comment by JakubMelka** [comment]
Hello,
I think it will be best solution (and I will be happy if you do it). Commits to the repository PDF4QT require the signing of the CLA, but this is another repository, so I think it is not needed. However, I will then need access to the repository - if some changes are needed (for example, I would like to add description and screenshots of the application).

I have four GUI applications, can flatpack create icons and shortcuts for them?

Thank you!

**Comment by jointri** [comment]
I would honestly suggest asking on https://discourse.flathub.org/ for any questions about flatpak who may know more than I do about how flatpak works.

**Comment by JakubMelka** [comment]
PDF4QT is published on flatpak:

https://flathub.org/apps/io.github.JakubMelka.Pdf4qt
