### ISSUE TITLE
Add pictures in PDF files

### ISSUE THREAD

**Issue by WttBe** [JakubMelka/PDF4QT#26]
Hi,

It would be really nice to have the opportunity to add pictures (.jpg, .png, etc.) to pdf files. Do you think it could be added to your software in the future?

Thanks anyway for the useful software!

**Comment by JakubMelka** [comment]
Hello,

yes, I am planning to create editing plugin, which can insert images. However, workaround exists:

- **Create PDF from image portfolio**:  by using PDF4QT DocPage Organizer. Via _Insert_ menu, select _Insert Image_ and insert all images. When all images are inserted, you can use command _United Document_ from _Make_ menu (F5 shortcut) and then PDF document with all images is created (each image has it's own page)
- **Insert image by hacking Signature plugin**: another option, if you want to place image onto existing page, you can enable **Signature** plugin trough Plugins tab in Options dialog (shortcut: Ctrl + K). Then, start activate signature creation, insert image via tool and when you are finished, click _Sign Electronically_. SVG images should work, I will also add support for PNG/JPEG.

I hope it will help!

**Comment by notshi** [comment]
> Insert image by hacking Signature plugin: another option, if you want to place image onto existing page, you can enable Signature plugin trough Plugins tab in Options dialog (shortcut: Ctrl + K). Then, start activate signature creation, insert image via tool and when you are finished, click Sign Electronically. SVG images should work, I will also add support for PNG/JPEG.

Thank you for having this option! Is this possible to do with the current version?  
I seem to be having problems trying to activate a signature creation or inserting image via tool. Appreciate your help!

**Comment by JakubMelka** [comment]
Hello @notshi , yes, it is possible. I assumed you turned on Signature plugin and restarted the application.
![image](https://github.com/JakubMelka/PDF4QT/assets/11367048/952079b7-5a6d-4263-b458-f06cea7cec00)

**Comment by notshi** [comment]
Hi @JakubMelka, yes, it was enabled by default (there was already a tick on factory settings).

![Screenshot_20230928_112105](https://github.com/JakubMelka/PDF4QT/assets/1515961/26284e59-6e29-4816-8cdb-2212e81eb5ba)

Upon restarting the application, this is what I see.

![Screenshot_20230928_112531](https://github.com/JakubMelka/PDF4QT/assets/1515961/ad0065f7-9b25-4fc6-93d1-5a6a4a1925ba)

I'm currently running PDF4QT Viewer Profi 1.3.5 on Manjaro Linux.

**Comment by notshi** [comment]
@JakubMelka Amazing ~ thank you very much! This has solved it for me and i can add svg images to the PDF seamlessly now.

Would it be possible to change the theme or colours of the icons?
At the moment, it looks dark and hard to see.

![Screenshot_20230928_144957](https://github.com/JakubMelka/PDF4QT/assets/1515961/38d7cfa8-05c8-45fe-854c-3a9369bba42b)

**Comment by JakubMelka** [comment]
I think it overtakes system settings - try to set light theme to your system.

**Comment by JakubMelka** [comment]
Hello @WttBe, new plugin Editor now can add images (also svg images, text, paths etc.)

**Comment by WttBe** [comment]
Hi @JakubMelka, Thanks a lot! I'll take a look at it!

**Comment by JakubMelka** [comment]
Hello @Osiris-Team, I tried it in the latest version and it works. Do you really use the latest version?

**Comment by Osiris-Team** [comment]
@JakubMelka did you try with a .png file? For me the image disapears after clicking on "Sign electronically".
