### ISSUE TITLE
Add multiple PDF files at once for merging?

### ISSUE THREAD

**Issue by xianghongai** [JakubMelka/PDF4QT#28]
Now only one file can be added at a time, which is inconvenient to operate.

Great tool, thank you for your effort.

**Comment by JakubMelka** [comment]
Hello,

I have added possibility to select multiple files via open dialog to add multiple files.

- multiple PDF files can be added via 'Add Documents...' action
- multiple images can be inserted via 'Insert Image' action

Please have a look on it, it is in the upstream.

**Comment by JakubMelka** [comment]
Merged in the upstream.
