### ISSUE TITLE
Feature requests: Reset Option

### ISSUE THREAD

**Issue by zdenop** [JakubMelka/PDF4QT#34]
Can you please implement "Reset option" (to default)?

I tried to play with speech settings  (PDF4QT - 1.3.0 Winter Release, Windows 10 64bit) and Pdf4QtViewerProfi/Pdf4QtViewerLite now crash when I hit CTRL+K, so even I do not see setting widget.

If it helps: As far as I remember I changed engine from sapi to winrt and then it crashed (first time).

**Comment by JakubMelka** [comment]
Hello,

I am sad the crash occurs. When I was moving to Qt 6, I also got crashes in winrt (implemented in Qt 6.4), but only in the debug build. It seems that new features in Qt 6.4 are buggy. I will add Reset option, as you requested.

Quick fix: navigate to following folder:
C:\Users\\"**user**"\AppData\Roaming\MelkaJ

Where "**user**" is your windows account name. There are stored files with settings. Delete all ini files and it should work.
Configuration file for PDF4QT Viewer Lite: **PDF4QT Viewer Lite.ini**
Configuration file for PDF4QT Viewer Profi: **PDF4QT Viewer Profi.ini**

**Comment by JakubMelka** [comment]
What operating system do you have? Please search for file "PDF4QT Viewer Profi.ini" on your hard drive and delete it.

**Comment by JakubMelka** [comment]
New version 1.3.1 of the program has been released. Contains option "Reset to Factory Settings" in the tool menu. @zdenop, could you please try it?

**Comment by zdenop** [comment]
Thanks! Now after "Reset to Factory Settings" the Options dialog is shown! 
(First I just tried CTRL+K in the new version, but it crashed too...)
