### ISSUE TITLE
cmake doesn't find lcms

### ISSUE THREAD

**Issue by ec1oud** [JakubMelka/PDF4QT#37]
```
CMake Error at CMakeLists.txt:50 (find_package):
  By not providing "Findlcms.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "lcms", but
  CMake did not find one.

  Could not find a package configuration file provided by "lcms" with any of
  the following names:

    lcmsConfig.cmake
    lcms-config.cmake

  Add the installation prefix of "lcms" to CMAKE_PREFIX_PATH or set
  "lcms_DIR" to a directory containing one of the above files.  If "lcms"
  provides a separate development package or SDK, be sure it has been
  installed.
```
Happens on Arch Linux.  Do other distros include cmake config files?

**Comment by JakubMelka** [comment]
Hello, strange. Please check what VCKPG do. I am not a linux expert - but if VCPKG is configured right, it should download the lcms. It works on latest Ubuntu.

**Comment by ec1oud** [comment]
I've never  needed vcpkg before, but ok there's a package for that.  It tells me this after installation:
```
  ==> vcpkg user note:
  ------------------------------------------------------------------------------
    "VCPKG_ROOT" is set to "/opt/vcpkg"
    "VCPKG_DOWNLOADS" is set to "/var/cache/vcpkg"
    To cooperate with CMake, add "-DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake"

    Please add the intended users to the group 'vcpkg':
    # gpasswd -a <user> vcpkg
```
So I tried:
```
$ cmake . -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake
```
It seems to pull in a lot of dependencies as source packages.  All dependencies are already on my system, so I'd normally expect to use the system libraries, not build redundant copies of them.

Then I just get a lot of compilation errors about type conversions, mostly from size_type to various things.

**Comment by JakubMelka** [comment]
Here is a minimal example (tested on MS Windows only, but it should not be system dependent) to build it using Qt Creator.
| Key                             | Value                                                        |
| ------------------------------- | -------------------------------------------------------------|
| `CMAKE_BUILD_TYPE`              | Debug                                                        |
| `CMAKE_CXX_COMPILER`            | %{Compiler:Executable:Cxx}                                   |
| `CMAKE_C_COMPILER`              | %{Compiler:Executable:C}                                     |
| `CMAKE_GENERATOR`               | Ninja                                                        |
| `CMAKE_PREFIX_PATH`             | %{Qt:QT_INSTALL_PREFIX}                                      |
| `CMAKE_PROJECT_INCLUDE_BEFORE`  | %{IDE:ResourcePath}/package-manager/auto-setup.cmake         |
| `CMAKE_TOOLCHAIN_FILE`          | %{Qt:QT_INSTALL_PREFIX}/lib/cmake/Qt6/qt.toolchain.cmake     |
| `PDF4QT_QT_ROOT`                | C:/Programming/Qt/6.4.0/msvc2019_64                          |
| `QT_QMAKE_EXECUTABLE`           | %{Qt:qmakeExecutable}                                        |

Variable `PDF4QT_QT_ROOT` must be set manually on your system.
Could you please check these variables?

I have following questions:
- What version of the compiler do you have?
- What version of the system do you have?

If it does not helps, I will install Arch Linux on Virtual Machine and check it...

**Comment by JakubMelka** [comment]
Hello, @ec1oud , what GCC version do you have? PDF4QT requires at least 11.

**Comment by JakubMelka** [comment]
I am closing it - no answer for 2 months. Please reopen, if you feel that it should be solved somehow.

**Comment by landryb** [comment]
Hi, for what it's worth i'm hitting the same issue when porting pdf4qt on OpenBSD, and there's no way we're going to allow a build system to download things on the fly.

Rather it should detect the presence of the existing lcms2 installation, either by providing a Findlcms.cmake module, or by using standard detection.

trying with a random cmake module taken from https://github.com/uclouvain/openjpeg/blob/master/cmake/FindLCMS2.cmake it doesn't define the variable expected by Pdf4QtLibCore/CMakeLists.txt:
```
CMake Error at Pdf4QtLibCore/CMakeLists.txt:165 (target_link_libraries):
  Target "Pdf4QtLibCore" links to:

    lcms2::lcms2
```

i don't know what vcpkg is nor how it interacts with cmake, but something is to be fixed imo, so please reopen..

**Comment by landryb** [comment]
configure succeeds with the cmake module above, and if i replace the `lcms2::lcms2` value by `${LCMS2_LIBRARY}` in Pdf4QtLibCore/CMakeLists.txt

**Comment by JakubMelka** [comment]
@landryb, I will try to use ${LCMS2_LIBRARY}.

**Comment by JakubMelka** [comment]
@landryb, it does not work, unfortunately.

**Comment by landryb** [comment]
i'm putting the porting aside for now, as afaict `std::execution::seq` relies on having libcxx built with _LIBCPP_HAS_PARALLEL_ALGORITHMS, which isn't the case for now on OpenBSD.
