### ISSUE TITLE
0xc0000005 since 1.3.0

### ISSUE THREAD

**Issue by r3sus** [JakubMelka/PDF4QT#38]
hey, thanks for the project.

I'm on win 7 x64 and get the 0xc0000005 error on launching PDF4QT*.exe in 1.3.0 (portable) / 1.3.1 (install). 
EXCEPTION_ACCESS_VIOLATION thrown in ntdll while api-ms-win-core-synch-l1-2-0.dll is closest in the stack. where that DLL shows C:\Program Files\Eclipse Adoptium\jdk-17.0.5.8-hotspot\bin and System32. Renaming the first makes no sense. 
msvc 2022 32/64 install didn't solve the issue. 
(from learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)

1.2.1 (portable): 
both viewer windows are blank, but I could trigger toolbar - [vid](https://user-images.githubusercontent.com/49620111/215081359-84f854e0-e0ed-471a-bef7-06c98e6837fc.mp4) - same for default and classic themes. 
organizer crashes in qt5gui. 
diff works well. 
same for older releases.

Please, have a look.
assume it's just for win10+. 
also: I could suggest adding program version to dist file name; 1.3.1 release info has a typo: msi 2 times.

**Comment by JakubMelka** [comment]
Hello,
thank you for the issue. On the Windows platform, I will support OS version supported by Microsoft - Windows 10+. Unfortunately, Qt has abandoned support for Windows7/8 as well (see https://www.qt.io/blog/qt6-development-hosts-and-targets )

Some ideas:
- PDF4QT uses hardware acceleration, and needs certain version of OpenGL to work (that can be cause for the white screen)
- Qt6 does not support Windows 7/8
- Explorer plugin could cause the crash - does it crash in open dialog?
- Previous version based on Qt5 were working?

Can you please add full callstack, where does it crash?

**Comment by JakubMelka** [comment]
And I am sorry for the typos. I will be more careful next time.

**Comment by r3sus** [comment]
Hey, thanks for the informative reply.
> PDF4QT uses hardware acceleration, and needs certain version of OpenGL to work (that can be cause for the white screen)

my notebook has two GPUs: loading with dedicated GPU makes 1.2x work fine, thanks.
> Qt6 does not support Windows 7/8

related workaround 
https://forum.qt.io/topic/133002/qt-creator-6-0-1-and-qt-6-2-2-running-on-windows-7/2
which doesn't helps with 1.3x binaries, it misses isChar@QXmlUtils@@SA_N_U@Z in Qt6Core.dll
> Explorer plugin could cause the crash - does it crash in open dialog?

on exe start. it's solved by GPU switch.
> Previous version based on Qt5 were working?

<1.2 (book icon) crash
> Can you please add full callstack, where does it crash?

sure
1.3.1 VL
[cs.txt](https://github.com/JakubMelka/PDF4QT/files/10539343/cs.txt)
[st2.txt](https://github.com/JakubMelka/PDF4QT/files/10539344/st2.txt)

> And I am sorry for the typos. I will be more careful next time.

np, release info could be edited anytime.
_
Regards.

**Comment by JakubMelka** [comment]
Hello @r3sus , PDF4QT requires at least Qt 6.4 (because of missing functionality in previous Qt6 versions). You can try it with Qt 6.4 or newer?

**Comment by HackYardo** [comment]
I'm on Win7 and have the same error 0xc0000005. Could I use a old version of pdf4Qt to avoid the error? Which version should I download?

**Comment by JakubMelka** [comment]
Hello, last version of the software, which should run on old system, is 1.2.1.

**Comment by HackYardo** [comment]
Thank you @JakubMelka very much. It works now. And the PDF4QT software is awesome.
