### ISSUE TITLE
Black preview page

### ISSUE THREAD

**Issue by dotty37** [JakubMelka/PDF4QT#45]
Hi
All my files show in black inside the preview window, and I cannot find the reason. 
I need to organize my pages but I cannot see each file, they all show in black.
Im attaching a test file here.
Thanks a lot !!
[TestFile.pdf](https://github.com/JakubMelka/PDF4QT/files/11113200/TestFile.pdf)

**Comment by JakubMelka** [comment]
Hello, I am able to simulate it. The problem is in Qt's hardware rendering, for some reason. If I use software rendering for PDF4QT DocPage Organizer, everyting seems to be OK. I will tomorrow have a look on it.

**Comment by JakubMelka** [comment]
Hello @dotty37 : I have added a patch, could you please test it, if it is OK?

**Comment by dotty37** [comment]
> Hello @dotty37 : I have added a patch, could you please test it, if it is OK?

Hi !,, can you point me to a place where I can download the installation file for Windows? the last release I see is from Feb 1st.
Thanks a lot again.

**Comment by JakubMelka** [comment]
Hello @dotty37 , new release is prepared. Could you please try it?

**Comment by dotty37** [comment]
> Hello @dotty37 , new release is prepared. Could you please try it?

Works great !! no longer black pages on preview !!. You are the best. Thanks a lot for working on this amazing piece of software !!
