### ISSUE TITLE
Program does not launch/freezes on Windows 10/Windows Server 2022 (x64)

### ISSUE THREAD

**Issue by ondrejvrabel** [JakubMelka/PDF4QT#46]
Hi, when I tried installing the program and launching Viewer Profi and Viewer Lite, only a blank window shows up, program freezes and then after a few seconds crashes. I did not find any logs which I could attach nor I didn't get any error messages. 

Page Organizer does not launch at all.

Doc Diff seems to work normally. 

I tried the program on Macbook with Apple Silicon M1 in Paralells (macOS) Windows 11 VM and everything worked properly.

<img width="1166" alt="Screenshot 2023-04-12 at 20 16 22" src="https://user-images.githubusercontent.com/30723938/231548713-a75ee9e0-d95c-4b31-a267-f99a345aa9a8.png">

<img width="1045" alt="Screenshot 2023-04-12 at 20 16 39" src="https://user-images.githubusercontent.com/30723938/231548689-1f42e169-989d-4f58-ad33-893638699fee.png">

**Comment by JakubMelka** [comment]
Hello, could you please provide more information?

- What is the system, where crash occurs?
- Graphic card type and version?
- Is it a virtual machine?
- Is there any unusualy settings or software?

**Comment by ondrejvrabel** [comment]
Hi, 
one of them is Azure virtual machine and other is Windows Server 2022 on Hyper-V Hypervisor, so both of them are VMs.
There aren't any other unusual settings or SW. The first machine is basically freshly installed VM with Windows 10, the other one is used for a bit longer.

**Comment by JakubMelka** [comment]
Well, I suspect there is problem with OpenGL. My software uses hardware acceleration and requires graphic card. Do these VMs have a graphic card? Which version of OpenGL can they provide?

Could you please try this:

- Go to https://mesa3d.org/
- Download software OpenGL implementation
- Copy OpenGL dlls from Mesa to the directory where binaries of PDF4QT are

**Comment by JakubMelka** [comment]
Question: is these Azure virtual machines accessible to single individual developers as me? Maybe I can register on Azure and examine it myself. How to do that?

**Comment by ondrejvrabel** [comment]
Yes, Azure has free trial available - https://azure.microsoft.com/en-us/pricing/offers/ms-azr-0044p/
We are using Windows 10 Pro VM.

**Comment by JakubMelka** [comment]
Hello @ondrejvrabel , new release is prepared where this issue should be fixed. Could you please try it?

**Comment by ondrejvrabel** [comment]
Just tried it, the issue is fixed. 
Got an alert notifying me about unavailability of HW acceleration.
<img width="726" alt="Screenshot 2023-04-22 at 15 36 25" src="https://user-images.githubusercontent.com/30723938/233788307-37be61e0-08aa-439d-a140-a388c1ce47c6.png">

Thank you!
