### ISSUE TITLE
page not displaying correctly

### ISSUE THREAD

**Issue by arcdipesh** [JakubMelka/PDF4QT#48]
contents of page offsets while opening pdf's exported by certain application like revit ,opens correctly else where.
[resting place--1.pdf](https://github.com/JakubMelka/PDF4QT/files/11241152/resting.place--1.pdf)

**Comment by JakubMelka** [comment]
Hello, it was a minor issue, I have provided a patch.

**Comment by arcdipesh** [comment]
Thanks,but now i am stuck in download page of qt ,it asks for business email to download free evaluation. so can't compile myself.

**Comment by JakubMelka** [comment]
I am planning to create a new release in a week or two, so you can then try it.

**Comment by JakubMelka** [comment]
Hello, new version has been released containing fix of this issue.

**Comment by arcdipesh** [comment]
Thank you very much.
