### ISSUE TITLE
Document read error

### ISSUE THREAD

**Issue by arcdipesh** [JakubMelka/PDF4QT#49]
Can't open some pdf. Shows error when opening given pdf.
[D A100 PLANS-D-AR 04.pdf](https://github.com/JakubMelka/PDF4QT/files/11296901/D.A100.PLANS-D-AR.04.pdf)
*opens correctly elsewhere.

**Comment by JakubMelka** [comment]
Hello @arcdipesh , I have fixed it and prepared a new release. Could you please try it?

**Comment by arcdipesh** [comment]
Thanks,it works now.
