### ISSUE TITLE
some types of pdf don't open as expected and some doesnt open.

### ISSUE THREAD

**Issue by arcdipesh** [JakubMelka/PDF4QT#50]
Hello,I tested some pdfs variety and found some problems opening certain types of pdfs, some display blank page, .The files with problems opening in pdf4qt is attached.Opens corectly elsewhere.
[Graphics-wpf.pdf](https://github.com/JakubMelka/PDF4QT/files/11304121/Graphics-wpf.pdf)
[00007.pdf](https://github.com/JakubMelka/PDF4QT/files/11304122/00007.pdf)
[Apr2000.pdf](https://github.com/JakubMelka/PDF4QT/files/11304127/Apr2000.pdf)

**Comment by arcdipesh** [comment]
also this pdf doesn't shows up text.
[Body 01 Drawing.pdf](https://github.com/JakubMelka/PDF4QT/files/11322696/Body.01.Drawing.pdf)

**Comment by JakubMelka** [comment]
The issue has been resolved in version 1.3.4. Should you believe the problem persists, please do not hesitate to reopen the issue.
