### ISSUE TITLE
System certificates store - not found

### ISSUE THREAD

**Issue by msavli** [JakubMelka/PDF4QT#55]
Using win10 I can not use system certificates store

![slika](https://github.com/JakubMelka/PDF4QT/assets/13658822/4dc2625b-764c-4c58-9fa6-f043a4d3a986)

![slika](https://github.com/JakubMelka/PDF4QT/assets/13658822/1497bd09-e008-4c6e-8491-6d0e49d3ca35)

![slika](https://github.com/JakubMelka/PDF4QT/assets/13658822/35fff885-5ce9-4640-93a8-154ac25830d7)

But in Edge i can found my system certificate store

![slika](https://github.com/JakubMelka/PDF4QT/assets/13658822/097e1f00-0841-42f6-a0aa-9edce03a6fe6)

Installed under user with limited rights or using zip. Result is the same. I can not use  system certificates store.
Is there any help available regarding this?

**Comment by JakubMelka** [comment]
Hello @msavli , so you want to sign a file with certificate installed in system certificate store? Could you please provide a sample certificate with password 12345?

**Comment by msavli** [comment]
Where can I get a sample certificate and what is a safe way to deliver it
to you, because one that I created is based on my email address.



       ------------   Marjan   ----------
        e-mail: ***@***.***
       --------------------------------------


V V sob., 1. jul. 2023 ob 17:23 je oseba Jakub Melka <
***@***.***> napisala:

**Comment by JakubMelka** [comment]
Hello @msavli , I will create certificate by myself, just tell me its parameters.

**Comment by msavli** [comment]
My wish is when signing certificate to pop-up this window:
https://user-images.githubusercontent.com/13658822/247086657-097e1f00-0841-42f6-a0aa-9edce03a6fe6.png
This is usual window with certificates (only that is in slovenian langugage)

I do not understand why I should you send certificate.

**Comment by JakubMelka** [comment]
OK, I will try to create my own certificate. I just wanted sample testing certificate from you.

**Comment by JakubMelka** [comment]
Hello @msavli, you can now select the certificate from the system certificate store using the dialog. Please give it a try.
