### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by raffaem** [JakubMelka/PDF4QT#56]
I have generated the Makefile using CMake, the running make:

```
[ABRIDGED]/PDF4QT/Pdf4QtLib/sources/pdfsignaturehandler.cpp:1947:15:   required from here
/usr/include/c++/13.1.1/type_traits:2610:11: error: no type named ‘type’ in ‘struct std::enable_if<false, QDataStream&>’
 2610 |     using enable_if_t = typename enable_if<_Cond, _Tp>::type;
      |           ^~~~~~~~~~~
```

I have Arch Linux

**Comment by JakubMelka** [comment]
Hello @raffaem, what version of GCC did you use?

**Comment by raffaem** [comment]
```
❯ gcc --version
gcc (GCC) 13.1.1 20230429
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by JakubMelka** [comment]
@raffaem, I have Ubuntu 23.04, I will have a look on it tomorrow, if it compiles under GCC 13.1.1.

**Comment by JakubMelka** [comment]
I have tried it on Ubuntu 23.04 with gcc 13.01. I found one compiler error and have fixed it. @raffaem , could you please pull new version and try it?

**Comment by raffaem** [comment]
Yes it compiles.

Although I don't understand this error when I do `sudo make install`:

```
-- Installing: [ABRIDGED]/PDF4QT/build/install/bin/
CMake Error at cmake_install.cmake:133 (file):
  file INSTALL cannot duplicate symlink

    /bin

  at

    [ABRIDGED]/PDF4QT/build/install/bin/

  because: A directory already exists at that location


make: *** [Makefile:100: install] Error 1
```

**Comment by JakubMelka** [comment]
To @raffaem : This happened to me too. There is a symlink to the previous build and install tries to make a new one. I think you can safely ignore it. Or you can just delete old symlink and it will work.

**Comment by raffaem** [comment]
But I don't think `sudo make install` installed the software system-wide. That is, I don't think it copied executables in /usr/local/bin.

**Comment by JakubMelka** [comment]
I think it tries to create symlink, which is already existing. Could you please delete the symlink and see what happens?

**Comment by raffaem** [comment]
What symlinks I have to delete? There is a folder ./install, but if I delete it the same error it shown

**Comment by raffaem** [comment]
Redirected to #61
