### ISSUE TITLE
Missing FindLCMS2.cmake

### ISSUE THREAD

**Issue by raffaem** [JakubMelka/PDF4QT#57]
Maybe it's my CMake distribution (I'm on Arch Linux), but I'm missing `FindLCMS2.cmake` CMake module.

This causes CMake to fail at [this line](https://github.com/JakubMelka/PDF4QT/blob/478c62df31836eff8d244a40c31a285ca7e9f3ee/CMakeLists.txt#L50).

There are various versions online, the one that works for me is [WebKitGTK+'s one](https://fossies.org/linux/webkitgtk/Source/cmake/FindLCMS2.cmake), since it has the `add_library`).

But in `CMakeLists.txt`, the line:
```
find_package(lcms REQUIRED)
```

Must be substituted with:
```
find_package(LCMS2 REQUIRED)
```

and [this line](https://github.com/JakubMelka/PDF4QT/blob/478c62df31836eff8d244a40c31a285ca7e9f3ee/Pdf4QtLib/CMakeLists.txt#L114) must be substituted with:
```
target_link_libraries(Pdf4QtLib PRIVATE LCMS2::LCMS2)
```

Then the compilation goes on until I hit #56

**Comment by JakubMelka** [comment]
Hello @raffaem, did you use it together with vcpkg? lcms is package for VCPKG and it works.

**Comment by raffaem** [comment]
Oh I see.

Can we have compilation instructions for the command line?

I may evaluate whether to pack it on the AUR

**Comment by raffaem** [comment]
I figured it out, but I still get #56
