### ISSUE TITLE
PDF Doc with rotated type3 fonts

### ISSUE THREAD

**Issue by ThomasKrenn** [JakubMelka/PDF4QT#58]
Hello Jakub,
excellent piece of work. I hope you find the time to continue to work on the project.

The enclosed file is PDF/A compatible but uses a lot of rotations and crashes the viewer (Tested on Win 10).

Best regards
Thomas

[rot_test_-1.pdf](https://github.com/JakubMelka/PDF4QT/files/11926882/rot_test_-1.pdf)

**Comment by JakubMelka** [comment]
Hello @ThomasKrenn ,

thank you! I have look at it and unfortunately, it is a bug in Qt. I have filed a bugreport: 
https://bugreports.qt.io/browse/QTBUG-115003 

I will try to somehow bypass it.

**Comment by ThomasKrenn** [comment]
Hello Jakub,
thanks for your feedback. I hope you don't mind if I send a few more documents.

Best regards
Thomas

**Comment by JakubMelka** [comment]
Hello @ThomasKrenn, OK, attach them in this issue and I will have a look on them.

**Comment by JakubMelka** [comment]
To @ThomasKrenn: I have reported the bug to Qt Company, they assigned it a critical priority and it is fixed by now. We will just wait for new Qt version (6.6).

**Comment by JakubMelka** [comment]
The issue has been addressed with Qt 6.6. I'm closing this and will release an update.
