### ISSUE TITLE
Text2Speech doesn't work on Linux

### ISSUE THREAD

**Issue by raffaem** [JakubMelka/PDF4QT#65]
Maybe I'm missing something, but the "Speech" tab seems not to work on Linux (I'm using Arch Linux).

The two text boxes are just empty:

![image](https://github.com/JakubMelka/PDF4QT/assets/54762742/b2e96b66-b694-47b2-b38e-b2b747d054a1)

What are they supposed to contain?

I have `qt6-speech` installed.

I don't know what's going wrong since I don't get any output in the console.

**Comment by raffaem** [comment]
I made it work partially with flite.

So first things first: we need to sort out the engines

1. flite -> https://github.com/festvox/flite
2. speechd -> https://github.com/brailcom/speechd
3. mock -> ? what is this? is this a real engine or just for testing purposes?

**Comment by JakubMelka** [comment]
@raffaem, yes, it requires some libraries for speech synthethis, for example, flite or speechd.

mock is engine only for test purposes.

**Comment by raffaem** [comment]
Also, we need an error message if the engine is not found in the system. It can't just fail silently.

**Comment by JakubMelka** [comment]
I will add warning message if no voice engine is found. On MS Windows, voice synthethiser is installed by default, so I thought the linux is the same.

**Comment by raffaem** [comment]
> I will add warning message if no voice engine is found. On MS Windows, voice synthethiser is installed by default, so I thought the linux is the same.

Some distros don't even install a desktop environment. Like Arch :p

**Comment by raffaem** [comment]
The flite engine just stops after a few words ... I don't know why because it just silently fails.

I can't code in QT.

I was not even able to setup the speechd engine.

**Comment by JakubMelka** [comment]
I think this is Qt issue. I am not doing anything special.

**Comment by JakubMelka** [comment]
I have added an error message.

**Comment by raffaem** [comment]
It works now, at least with flite
