### ISSUE TITLE
Dashed Line not rendered as expected

### ISSUE THREAD

**Issue by ThomasKrenn** [JakubMelka/PDF4QT#69]
Hello @JakubMelka,
enclosed is a document that uses the c operator to draw a dashed line. The line is drawn, but the length of the dashes is too long.

[rotate.pdf](https://github.com/JakubMelka/PDF4QT/files/12049572/rotate.pdf)

Best regards
Thomas

**Comment by JakubMelka** [comment]
Hello @ThomasKrenn,

I have fixed it now. Next week, I am planning to create a new release of PDF4QT.

**Comment by JakubMelka** [comment]
The issue has been resolved in version 1.3.4. Should you believe the problem persists, please do not hesitate to reopen the issue.
