### ISSUE TITLE
Pages are displayed "mirrored"

### ISSUE THREAD

**Issue by ThomasKrenn** [JakubMelka/PDF4QT#71]
Hello @JakubMelka,

the pages of the enclosed test document have all kinds of rotations. The pages 2, 5, 11, 12 and 13 are rotated but they are displayed "mirrored" on the y-axis.

[rotated.pdf](https://github.com/JakubMelka/PDF4QT/files/12169380/rotated.pdf)

Best regards
Thomas

**Comment by JakubMelka** [comment]
Hello, I will have a look on it today.

**Comment by ThomasKrenn** [comment]
Hello @JakubMelka,
thanks for your feedback.

No worry! It's summertime and it's open source.

Best regards
Thomas

**Comment by JakubMelka** [comment]
Hello @ThomasKrenn, it should be fixed now.

**Comment by JakubMelka** [comment]
The issue has been resolved in version 1.3.4. Should you believe the problem persists, please do not hesitate to reopen the issue.
