### ISSUE TITLE
Minor GUI issues

### ISSUE THREAD

**Issue by ThomasKrenn** [JakubMelka/PDF4QT#73]
Hello @JakubMelka,
menu entries that show a dialog before the action should have an ellipsis (...) in the name. 

E.g.
Open...
Save as...
Print...
Render to Images...
Advanced Find...

The default shortcut for "Close" (file menu) should be Ctrl-W

Best regards
Thomas

**Comment by JakubMelka** [comment]
I've addressed the issues you mentioned. Actions that trigger a dialog now have three dots following them in the menu. I've also corrected the keyboard shortcuts and some texts. Moreover, my program allows you to redefine keyboard shortcuts according to your preferences. You can do this in the Options dialog. I hope this helps!

**Comment by JakubMelka** [comment]
The issue has been resolved in version 1.3.4. Should you believe the problem persists, please do not hesitate to reopen the issue.
