### ISSUE TITLE
[FR] Modify bookmarks

### ISSUE THREAD

**Issue by raffaem** [JakubMelka/PDF4QT#76]
Ability to add/delete/edit bookmarks

**Comment by JakubMelka** [comment]
Implemented.

**Comment by raffaem** [comment]
This is excellent work:

![image](https://github.com/JakubMelka/PDF4QT/assets/54762742/e78b3fc4-f05d-415e-a885-449eb06ad02c)

You can follow the bookmark, delete or rename it, insert a new bookmark, change font style, and change the destination of the bookmark, including the ability to set page or bounding box.

The only thing I don't understand why I have to draw a rectangle when I set a page as the destination.

Also, I would add an option like "Current View", that sets the target to the current view.

Kudos to @JakubMelka !
