### ISSUE TITLE
Document read error

### ISSUE THREAD

**Issue by arcdipesh** [JakubMelka/PDF4QT#77]
cannot read this pdf opens correctly elsewhere
[I WORKING DRAWING_edit_.pdf](https://github.com/JakubMelka/PDF4QT/files/12265316/I.WORKING.DRAWING_edit_.pdf)
![image](https://github.com/JakubMelka/PDF4QT/assets/50439654/1c21cbb3-ab36-4575-91f3-b468153b01b7)

**Comment by JakubMelka** [comment]
I have fixed it.
