### ISSUE TITLE
Errror decompressing stream

### ISSUE THREAD

**Issue by ThomasKrenn** [JakubMelka/PDF4QT#78]
Hello @JakubMelka ,
thanks a lot for the improvements, and congratulations to the new release. 

Please find below a document that has a stream (/ASCII85Decode /FlateDecode) that cannot be read.
This encoding was popular in the early days of PDF and was used by E-Books creators.

Best regards 
Thomas

[12 Finite-State Machines.pdf](https://github.com/JakubMelka/PDF4QT/files/12266380/12.Finite-State.Machines.pdf)

**Comment by JakubMelka** [comment]
I have fixed it. Thank you for testing!

**Comment by JakubMelka** [comment]
The bug has been fixed in the upstream, I am closing the issue.
