### ISSUE TITLE
can not install in Linux mint 21.2

### ISSUE THREAD

**Issue by ritulahkar** [JakubMelka/PDF4QT#79]
please make it able to install in LM21.2. Thank you in advance.

**Comment by JakubMelka** [comment]
Hello @ritulahkar , I have posted the application in Flathub, see https://flathub.org/apps/io.github.JakubMelka.Pdf4qt . It should work in Linux Mint. Please reopen the issue, if it does not.

**Comment by ritulahkar** [comment]
It is crashing on trying to open files. When calling from file manager, it can not find the file.

**Comment by JakubMelka** [comment]
I was able to reproduce crash too, it is crashing in gtk (in system library), and I do not know why. I think it can be a bug in Qt.

**Comment by JakubMelka** [comment]
OK, crash will be solved in another issue.
