### ISSUE TITLE
How to hide the content?

### ISSUE THREAD

**Issue by danhui82** [JakubMelka/PDF4QT#81]
I use signature with rectangle to hide the content, but I open the pdf with pdf reader, the hidden content will be shown about 0.5 second, please provide any solution to fix it🙏🙏

**Comment by JakubMelka** [comment]
We have not received a response for the past two weeks, thus I'm afraid I will have to conclude this thread. I would recommend considering the use of the redact plugin to hide content. Thank you for your understanding.
