### ISSUE TITLE
[Feature Request] Hot reload function

### ISSUE THREAD

**Issue by github-young** [JakubMelka/PDF4QT#82]
Thank you for developing this beautiful & DE-independent PDF reader.

I am a LaTeX user so I need to view the compiled PDF with a hot-reload function. It is very common in other PDF viewers including `` Evince/Qpdfview/Sumatra/... ``, but it seems not available in `` PDF4QT ``. Would you please consider adding this feature? Thank you.

**Comment by JakubMelka** [comment]
Hello, yes, it will be a good feature. I will look on it tomorrow.

**Comment by JakubMelka** [comment]
I am pleased to announce that the feature has been merged into the upstream. It was more challenging than I anticipated, and it took several days.
