### ISSUE TITLE
Installation of  PDF4QT-1.3.4.deb is not possible in Linux Mint

### ISSUE THREAD

**Issue by LinuxMUser** [JakubMelka/PDF4QT#84]
When installing PDF4QT-1.3.4.deb on Linux Mint 21.2 an error message occurs: "Dependency not achievable: libqt6texttospeech6". Manual installation of "libqt6texttospeech6" ends up into die message, that the package could not be found. 
It would be great, if you could fix this issue.

**Comment by JakubMelka** [comment]
Hello, PDF4QT requires at least Qt 6.4, while Linux Mint has packages for only Qt 6.2.4 version. What should I do? I am not a linux expert.

**Comment by JakubMelka** [comment]
Hello @LinuxMUser  , I have posted the application in Flathub, see https://flathub.org/apps/io.github.JakubMelka.Pdf4qt . It should work in Linux Mint. Please reopen the issue, if it does not.
