### ISSUE TITLE
doc page organizer extraction of bookmarks

### ISSUE THREAD

**Issue by Doty1154** [JakubMelka/PDF4QT#89]
Hey I'm trying to extract a set of bookmarks from large pdf's, i see that i can select sub-bookmarks using DocPage Organizer and group them, but the UI seems to just be subdividing the existing pdf into smaller groups but not selecting just the selected 
bookmarks.  

An of example of the behavior i'm trying to achieve would be:

- Colors
**-- Black**
-- Pink
-- Blue

- Animals
**-- Dogs**
-- Cats
-- Pigs

I chose Black & Dogs
Therefore i would like to export a pdf of just those selections:

-- Black
-- Dogs

Is this functionality of DocOrganizer or can it just select PDF pages that contain the bookmarks but not extract the book marked section?

**Comment by JakubMelka** [comment]
Hello! In this scenario, I recommend selecting all the subcategories: Black, Pink, Blue, Dogs, Cats, and Pigs. These will likely be segmented into six sections, with a possible seventh for introductory pages. Afterward, simply highlight the content you don't need (such as Pink/Blue and Cats/Pigs) and press the 'Del' key to remove them.

**Comment by JakubMelka** [comment]
Dear @Doty1154 ,

Ihave not received a response to this issue for a month, therefore I find it appropriate to close it for now. However, if you believe it still requires attention, please feel free to reopen it at your earliest convenience.

Thank you.
