### ISSUE TITLE
New directory structure

### ISSUE THREAD

**Issue by raffaem** [JakubMelka/PDF4QT#94]
I don't understand why the new git version as well as the `.deb` file has a directory structure like this:
```
❯ exa --tree
.
├── bin
│  ├── Pdf4QtDocDiff
│  ├── Pdf4QtDocPageOrganizer
│  ├── Pdf4QtViewerLite
│  ├── Pdf4QtViewerProfi
│  └── PdfTool
├── lib
│  ├── libPdf4QtLib.so -> libPdf4QtLib.so.1.3.5
│  ├── libPdf4QtLib.so.1.3.5
│  ├── libPdf4QtViewer.so
│  └── pdf4qt
│     ├── libAudioBookPlugin.so -> libAudioBookPlugin.so.1.3.5
│     ├── libAudioBookPlugin.so.1.3.5
│     ├── libDimensionsPlugin.so -> libDimensionsPlugin.so.1.3.5
│     ├── libDimensionsPlugin.so.1.3.5
│     ├── libObjectInspectorPlugin.so -> libObjectInspectorPlugin.so.1.3.5
│     ├── libObjectInspectorPlugin.so.1.3.5
│     ├── libOutputPreviewPlugin.so -> libOutputPreviewPlugin.so.1.3.5
│     ├── libOutputPreviewPlugin.so.1.3.5
│     ├── libRedactPlugin.so -> libRedactPlugin.so.1.3.5
│     ├── libRedactPlugin.so.1.3.5
│     ├── libSignaturePlugin.so -> libSignaturePlugin.so.1.3.5
│     ├── libSignaturePlugin.so.1.3.5
│     ├── libSoftProofingPlugin.so -> libSoftProofingPlugin.so.1.3.5
│     └── libSoftProofingPlugin.so.1.3.5
└── usr
   └── share
      ├── applications
      │  ├── Pdf4QtDocDiff.desktop
      │  ├── Pdf4QtDocPageOrganizer.desktop
      │  ├── Pdf4QtViewerLite.desktop
      │  └── Pdf4QtViewerProfi.desktop
      └── icons
         ├── Pdf4QtDocDiff.svg
         ├── Pdf4QtDocPageOrganizer.svg
         ├── Pdf4QtViewerLite.svg
         └── Pdf4QtViewerProfi.svg
```

This structure has changed from the previous one, causing problems like [this](https://aur.archlinux.org/packages/pdf4qt-git#comment-934838).

`/bin` contains programs needed for booting or repairing the system.
`/usr/bin` contains program installed by the user through its package manager.
So technically both `cmake --install` and the `.deb` file should install in `/usr/local`, while the Arch packages should install under `/usr`. Nothing should install under `/`.

**Comment by JakubMelka** [comment]
Hello,

I understand your perspective. The requirement was put in place by the administrators at Flatpak. I'm considering creating a "switch" in the cmake file that would allow us to set this path. This way, it would be possible to decide via the cmake option which directory the software will be installed in.

What are your thoughts on this?

**Comment by JakubMelka** [comment]
To @raffaem : I have solved the issue, introducing new option PDF4QT_INSTALL_TO_USR. It is defaultly switched OFF, use -DPDF4QT_INSTALL_TO_USR=ON to activate it.
