### ISSUE TITLE
Flatpak crashing on trying open file on Linux mint 21.2

### ISSUE THREAD

**Issue by ritulahkar** [JakubMelka/PDF4QT#95]
Flatpak version crashes when trying to open a file.
It can't find the file when trying to use it from file manager.

**Comment by JakubMelka** [comment]
Hello, I know about this. It crashes in the system library GTK and I do not know why. Ubuntu does not have this problem.

**Comment by Tirguy** [comment]
It seems that some lib are missed : 

```
thierry@thierry:~$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=Pdf4QtDocPageOrganizer io.github.JakubMelka.Pdf4qt
Gtk-Message: 00:06:22.426: Failed to load module "xapp-gtk3-module"
Gtk-Message: 00:06:22.426: Failed to load module "appmenu-gtk-module"
Qt: Session management error: Could not open network socket
```
I've also had the libqt6texttospeech6 was not installed... I've try to install all QT6 on my computer, but it's not enough

**Comment by JakubMelka** [comment]
Hello,
I am reaching out to seek your assistance with an issue I've encountered. As my expertise with Linux is limited, I am currently facing challenges in understanding why GTK is experiencing crashes. I would greatly appreciate any guidance or support you could provide to help resolve this matter.

**Comment by JakubMelka** [comment]
Hello  @ritulahkar, it should be fixed. Please try new flatpak version.
