### ISSUE TITLE
Can't install deb package for lacking QT package 

### ISSUE THREAD

**Issue by cross-hello** [JakubMelka/PDF4QT#98]
```shell
The following packages have unmet dependencies:
 pdf4qt : Depends: libqt6texttospeech6 but it is not installable
          Depends: qt6-speech-speechd-plugin but it is not installable
          Depends: qt6-speech-flite-plugin but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by JakubMelka** [comment]
Hello, which linux system do you have? Did you tried to use Flatpak?

**Comment by cross-hello** [comment]
Ubuntu 22.04(though it doesn't matter), the system don't install QT by default(so it don't have QT related package.

Oct 7, 2023 2:43:27 AM Jakub Melka ***@***.***>:

**Comment by JakubMelka** [comment]
Please try to update to Ubuntu 23.

**Comment by cross-hello** [comment]
Oh, it don't seem the matter of system.

Your system have installed Qt designer, which will carry those packages.

But for ones who not(QT need consent for not commercial use), oh 🙃

**Comment by JakubMelka** [comment]
@cross-hello,

Thank you for your message. I would like to inform you that during my testing, I have verified that the solution works seamlessly on a clean installation of Ubuntu version 23.

Regarding the issue with the packages (libqt6texttospeech6, qt6-speech-speechd-plugin, qt6-speech-flite-plugin), it is important to note that they were added in Ubuntu 23 as part of the Qt 6.4 implementation. Regrettably, the older version, Ubuntu 22, does not support these packages.

I strongly recommend you to upgrade to version 23. I am confident that this step will resolve the issues at hand.

Should you have any further questions or comments, please do not hesitate to contact me.

Best regards,
JM

**Comment by myviolinsings** [comment]
Linux Mint 21.2 and Pop OS 22.04 cannot be upgraded to 23.04 yet. No way to use the package without that.

**Comment by WilhelmVonHindenburger** [comment]
Linux Mint 21.2, same error (libqt6texttospeech6).

**Comment by fraterlinux** [comment]
> Hello, which linux system do you have? Did you tried to use Flatpak?

I would like to comment that Flatpak is not a good method for Linux. It installs an entire system within the distro to satisfy dependencies and doubles the size of /root
I would like to ask that AppImage be used as an alternative!

**Linux apps that run anywhere**

"As a user, I want to download an application from the original author, and run it on my Linux desktop system just like I would do with a Windows or Mac application."
https://appimage.org/

**Comment by JakubMelka** [comment]
Hello, yes, I am planning to do it.

**Comment by JakubMelka** [comment]
@cross-hello , @fraterlinux, I have prepared AppImage, please try it.

**Comment by cross-hello** [comment]
Thank you for notifications. 

This time it could run on Ubuntu 22.04 as is. 

Thank you~

**Comment by JakubMelka** [comment]
Perfect, closing as solved.
