### ISSUE TITLE
Icons for dark mode

### ISSUE THREAD

**Issue by sith-on-mars** [JakubMelka/PDF4QT#99]
Currently, the icon colour is designed for light mode only. Icons are difficult to read in dark mode. It would be great if we could have icons for dark mode.

![image](https://github.com/JakubMelka/PDF4QT/assets/37974764/a6d8fe88-2689-49cf-8a9f-23e12b6b8d8d)

**Comment by JakubMelka** [comment]
Hello, icons for dark mode are finished.
